/*
 * Deterministic frame engine.  frame = render(t, scene data, assets, fixed seeds)
 *
 * window.TIMELINE (src/timeline.js, generated by tools/timeline.py) owns all timing:
 *   { fps, duration, bpm, scenes: [{id, start, dur, theme, chapter, transition: {type, dur}}],
 *     lines: [{id, scene, text, start, end, subs: [{text, start, end}]}], chapters: [{id, num, label, start, end}] }
 * window.MEDIA (src/media/manifest.js, generated by tools/extract_clips.py):
 *   { <clipId>: {fps, frames, w, h, dir, src, srcStart, srcEnd} }
 *
 * Scenes call Scene.define({ id, build(root, ctx) -> state, render(state, t, ctx), events?(ctx) -> [{t, type, gain}] }).
 * t is local seconds from the scene start. During the next scene's transition-in the outgoing scene keeps rendering
 * with t > ctx.dur, so render() must handle t in [0, ctx.dur + nextTransitionDur].
 * Nothing may read the wall clock or Math.random(); use ctx.rng(seed) / M.noise*.
 */
(() => {
  'use strict';
  const W = 1920, H = 1080;

  // ---------------- math ----------------
  const clamp = (x, a = 0, b = 1) => Math.min(b, Math.max(a, x));
  const lerp = (a, b, p) => a + (b - a) * p;
  const invLerp = (a, b, x) => (b === a ? (x >= b ? 1 : 0) : clamp((x - a) / (b - a)));
  const pow = Math.pow;
  const ease = {
    linear: p => p,
    inQuad: p => p * p,
    outQuad: p => 1 - (1 - p) * (1 - p),
    inOutQuad: p => (p < 0.5 ? 2 * p * p : 1 - pow(-2 * p + 2, 2) / 2),
    inCubic: p => p * p * p,
    outCubic: p => 1 - pow(1 - p, 3),
    inOutCubic: p => (p < 0.5 ? 4 * p * p * p : 1 - pow(-2 * p + 2, 3) / 2),
    inQuart: p => p * p * p * p,
    outQuart: p => 1 - pow(1 - p, 4),
    inOutQuart: p => (p < 0.5 ? 8 * p * p * p * p : 1 - pow(-2 * p + 2, 4) / 2),
    outQuint: p => 1 - pow(1 - p, 5),
    inOutQuint: p => (p < 0.5 ? 16 * p * p * p * p * p : 1 - pow(-2 * p + 2, 5) / 2),
    inExpo: p => (p === 0 ? 0 : pow(2, 10 * p - 10)),
    outExpo: p => (p === 1 ? 1 : 1 - pow(2, -10 * p)),
    inOutExpo: p => (p === 0 ? 0 : p === 1 ? 1 : p < 0.5 ? pow(2, 20 * p - 10) / 2 : (2 - pow(2, -20 * p + 10)) / 2),
    inSine: p => 1 - Math.cos((p * Math.PI) / 2),
    outSine: p => Math.sin((p * Math.PI) / 2),
    inOutSine: p => -(Math.cos(Math.PI * p) - 1) / 2,
    outBack: p => { const c1 = 1.70158, c3 = c1 + 1; return 1 + c3 * pow(p - 1, 3) + c1 * pow(p - 1, 2); },
    inBack: p => { const c1 = 1.70158, c3 = c1 + 1; return c3 * p * p * p - c1 * p * p; },
    inOutBack: p => { const c2 = 1.70158 * 1.525; return p < 0.5 ? (pow(2 * p, 2) * ((c2 + 1) * 2 * p - c2)) / 2 : (pow(2 * p - 2, 2) * ((c2 + 1) * (p * 2 - 2) + c2) + 2) / 2; },
    outElastic: p => (p === 0 ? 0 : p === 1 ? 1 : pow(2, -10 * p) * Math.sin((p * 10 - 0.75) * ((2 * Math.PI) / 3)) + 1),
  };
  // eased 0..1 progress of a window [start, start + dur]
  const prog = (t, start, dur, e = ease.outCubic) => e(clamp((t - start) / Math.max(1e-6, dur)));
  // value in [a,b] -> [c,d] with optional easing
  const remap = (x, a, b, c, d, e = ease.linear) => lerp(c, d, e(invLerp(a, b, x)));
  // enter/hold/exit envelope: 0 -> 1 over [a, a+fi], stays 1, 1 -> 0 over [b-fo, b]
  const env = (t, a, b, fi = 0.4, fo = 0.4, ei = ease.outCubic, eo = ease.inCubic) =>
    Math.min(prog(t, a, fi, ei), 1 - prog(t, b - fo, fo, eo));
  // Damped spring step response (0 -> 1, may overshoot). t in seconds.
  function spring(t, { stiffness = 180, damping = 18, mass = 1 } = {}) {
    if (t <= 0) return 0;
    const w0 = Math.sqrt(stiffness / mass);
    const zeta = damping / (2 * Math.sqrt(stiffness * mass));
    if (zeta < 1) {
      const wd = w0 * Math.sqrt(1 - zeta * zeta);
      return 1 - Math.exp(-zeta * w0 * t) * (Math.cos(wd * t) + ((zeta * w0) / wd) * Math.sin(wd * t));
    }
    return 1 - Math.exp(-w0 * t) * (1 + w0 * t);
  }
  // seeded PRNG
  function rng(seed = 1) {
    let a = (typeof seed === 'string' ? hashStr(seed) : seed) >>> 0;
    const f = () => {
      a |= 0; a = (a + 0x6d2b79f5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
    f.range = (lo, hi) => lo + (hi - lo) * f();
    f.int = (lo, hi) => Math.floor(lo + (hi - lo + 1) * f());
    f.pick = arr => arr[Math.floor(f() * arr.length)];
    return f;
  }
  function hashStr(s) {
    let h = 2166136261;
    for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); }
    return h >>> 0;
  }
  // smooth value noise
  const hash1 = n => { const x = Math.sin(n * 127.1 + 311.7) * 43758.5453123; return x - Math.floor(x); };
  const hash2 = (x, y) => { const v = Math.sin(x * 127.1 + y * 311.7) * 43758.5453123; return v - Math.floor(v); };
  const sstep = p => p * p * (3 - 2 * p);
  function noise1(x) { const i = Math.floor(x), f = x - i; return lerp(hash1(i), hash1(i + 1), sstep(f)) * 2 - 1; }
  function noise2(x, y) {
    const ix = Math.floor(x), iy = Math.floor(y), fx = x - ix, fy = y - iy;
    const a = hash2(ix, iy), b = hash2(ix + 1, iy), c = hash2(ix, iy + 1), d = hash2(ix + 1, iy + 1);
    return lerp(lerp(a, b, sstep(fx)), lerp(c, d, sstep(fx)), sstep(fy)) * 2 - 1;
  }
  // colors
  function hex2rgb(hex) { const n = parseInt(hex.replace('#', ''), 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; }
  function mixColor(c1, c2, p) {
    const a = hex2rgb(c1), b = hex2rgb(c2);
    return `rgb(${Math.round(lerp(a[0], b[0], p))},${Math.round(lerp(a[1], b[1], p))},${Math.round(lerp(a[2], b[2], p))})`;
  }
  const rgba = (hex, a) => { const [r, g, b] = hex2rgb(hex); return `rgba(${r},${g},${b},${a})`; };

  const M = { clamp, lerp, invLerp, remap, ease, prog, env, spring, rng, hashStr, noise1, noise2, mixColor, rgba, hex2rgb };

  // ---------------- DOM helpers ----------------
  function h(tag, props = {}, ...children) {
    const el = document.createElement(tag);
    applyProps(el, props);
    for (const c of children.flat(Infinity)) if (c != null && c !== false) el.append(c.nodeType ? c : document.createTextNode(String(c)));
    return el;
  }
  const SVGNS = 'http://www.w3.org/2000/svg';
  function s(tag, props = {}, ...children) {
    const el = document.createElementNS(SVGNS, tag);
    for (const [k, v] of Object.entries(props)) {
      if (k === 'style' && typeof v === 'object') Object.assign(el.style, v);
      else if (k === 'text') el.textContent = v;
      else if (v != null) el.setAttribute(k, v);
    }
    for (const c of children.flat(Infinity)) if (c != null && c !== false) el.append(c.nodeType ? c : document.createTextNode(String(c)));
    return el;
  }
  function applyProps(el, props) {
    for (const [k, v] of Object.entries(props || {})) {
      if (v == null) continue;
      if (k === 'style' && typeof v === 'object') Object.assign(el.style, v);
      else if (k === 'class') el.className = v;
      else if (k === 'html') el.innerHTML = v;
      else if (k === 'text') el.textContent = v;
      else el.setAttribute(k, v);
    }
  }
  // Set transform + opacity in one call. Units: px, deg.
  function tf(el, o = {}) {
    const x = o.x || 0, y = o.y || 0, r = o.r || 0;
    const sx = o.sx != null ? o.sx : o.s != null ? o.s : 1;
    const sy = o.sy != null ? o.sy : o.s != null ? o.s : 1;
    let t = `translate(${x.toFixed(2)}px,${y.toFixed(2)}px)`;
    if (o.rx || o.ry) t += ` perspective(${o.persp || 1600}px) rotateX(${o.rx || 0}deg) rotateY(${o.ry || 0}deg)`;
    if (r) t += ` rotate(${r.toFixed(3)}deg)`;
    if (sx !== 1 || sy !== 1) t += ` scale(${sx.toFixed(4)},${sy.toFixed(4)})`;
    el.style.transform = t;
    if (o.o != null) el.style.opacity = clamp(o.o).toFixed(4);
    if (o.blur != null) el.style.filter = o.blur > 0.05 ? `blur(${o.blur.toFixed(2)}px)` : 'none';
    if (o.vis != null) el.style.visibility = o.vis ? 'visible' : 'hidden';
  }
  // Split text into per-character spans (keeps spaces). Returns the span array.
  function chars(el, text, cls = 'ch') {
    el.textContent = '';
    const out = [];
    for (const c of Array.from(text)) {
      const sp = document.createElement('span');
      sp.className = cls;
      sp.textContent = c;
      el.append(sp);
      out.push(sp);
    }
    return out;
  }
  // Typewriter: show first n characters of str for progress p
  const typed = (str, p) => { const a = Array.from(str); return a.slice(0, Math.round(clamp(p) * a.length)).join(''); };

  // ---------------- images / media ----------------
  const imgCache = new Map(); // url -> HTMLImageElement
  const pending = new Set();  // promises the current frame must wait on
  function image(url) {
    let im = imgCache.get(url);
    if (!im) {
      im = new Image();
      im.decoding = 'sync';
      im.src = url;
      imgCache.set(url, im);
      if (imgCache.size > 360) { // simple LRU-ish trim
        const first = imgCache.keys().next().value;
        imgCache.delete(first);
      }
    }
    if (!(im.complete && im.naturalWidth)) pending.add(im.decode().catch(() => {}));
    return im;
  }
  // Set <img> src for the frame; the frame waits until it is decoded.
  function setImg(el, url) {
    if (el.dataset.src === url) return;
    el.dataset.src = url;
    el.src = url;
    pending.add(el.decode().catch(() => {}));
    image(url);
  }
  // Use an image (e.g. a clip frame) as an element's CSS background; the frame waits for it to decode.
  function bgImg(el, url) {
    if (el.dataset.bg === url) return;
    el.dataset.bg = url;
    image(url);
    el.style.backgroundImage = `url("${url}")`;
  }
  // URL of a clip frame at local time t (seconds from clip start). mode: 'clamp' | 'loop' | 'pingpong'
  function clipUrl(id, t, mode = 'clamp') {
    const m = (window.MEDIA || {})[id];
    if (!m) throw new Error(`unknown clip ${id}`);
    let i = Math.floor(t * m.fps + 1e-6);
    if (mode === 'loop') i = ((i % m.frames) + m.frames) % m.frames;
    else if (mode === 'pingpong') { const p = 2 * (m.frames - 1); i = ((i % p) + p) % p; if (i >= m.frames) i = p - i; }
    else i = Math.max(0, Math.min(m.frames - 1, i));
    return `${m.dir}/f${String(i + 1).padStart(5, '0')}.jpg`;
  }
  const clipInfo = id => (window.MEDIA || {})[id];

  // ---------------- timeline & scenes ----------------
  const defs = new Map();
  const templates = new Map();
  const Scene = {
    define(def) { if (defs.has(def.id)) throw new Error('dup scene ' + def.id); defs.set(def.id, def); },
    // a template serves every timeline scene whose "template" (or "file") names it; per-scene params arrive in ctx.data
    template(name, def) { templates.set(name, def); },
  };
  let TL, stage, scenes = [], subsEl, subEl, chromeEl, chapterEl, chapterNum, chapterLabel, logoEl, progressEl, grainEl, wipebar, wipeEdge;
  let grainTiles = [];
  let debugEl = null;
  let vignetteEl = null, vignetteOut = null;
  const NOSUBS = /[?&]nosubs=1/.test(location.search);  // stills for covers/thumbnails

  function makeCtx(sc) {
    const lines = TL.lines.filter(l => l.scene === sc.id).map(l => ({
      ...l, start: l.start - sc.start, end: l.end - sc.start,
      words: (l.words || []).map(w => ({ ...w, start: w.start - sc.start, end: w.end - sc.start })),
    }));
    const byId = Object.fromEntries(lines.map(l => [l.id, l]));
    const beat = 60 / (TL.bpm || 120);
    const ctx = {
      id: sc.id, dur: sc.dur, start: sc.start, theme: sc.theme || 'dark', fps: TL.fps, W, H, lines, transition: sc.transition || { type: 'cut', dur: 0 },
      next: null, // filled after all scenes are known
      cue(id, fallback = 0) { const l = byId[id] || byId[`${sc.id}.${id}`]; return l ? l.start : fallback; },
      cueEnd(id, fallback = 0) { const l = byId[id] || byId[`${sc.id}.${id}`]; return l ? l.end : fallback; },
      // local time when a word (substring match on the TTS word list) is spoken in a line; nth occurrence
      word(id, w, nth = 0, fallback) {
        const l = byId[id] || byId[`${sc.id}.${id}`];
        if (!l) { (window.__cueMisses = window.__cueMisses || []).push({ scene: sc.id, line: id, word: String(w), noLine: true }); return fallback != null ? fallback : 0; }
        const needle = String(w).toLowerCase();
        const ms = l.words.filter(x => x.w.toLowerCase().includes(needle) || needle.includes(x.w.toLowerCase()) && x.w.length > 1);
        const m = ms[nth] || ms[0];
        if (!m) (window.__cueMisses = window.__cueMisses || []).push({ scene: sc.id, line: id, word: String(w) });
        return m ? m.start : (fallback != null ? fallback : l.start);
      },
      wordEnd(id, w, nth = 0, fallback) {
        const l = byId[id] || byId[`${sc.id}.${id}`];
        if (!l) return fallback != null ? fallback : 0;
        const needle = String(w).toLowerCase();
        const ms = l.words.filter(x => x.w.toLowerCase().includes(needle) || needle.includes(x.w.toLowerCase()) && x.w.length > 1);
        const m = ms[nth] || ms[0];
        if (!m) (window.__cueMisses = window.__cueMisses || []).push({ scene: sc.id, line: id, word: String(w), end: true });
        return m ? m.end : (fallback != null ? fallback : l.end);
      },
      line(i) { return lines[i]; },
      // local time of the nth beat at or after the scene start on the global music grid
      beatTime(n) { const g0 = Math.ceil(sc.start / beat - 1e-6) * beat; return g0 + n * beat - sc.start; },
      beat,
      rng: seed => rng(`${sc.id}:${seed}`),
      clipUrl, clipInfo, image, setImg,
      data: sc.data || {},
    };
    return ctx;
  }

  function init() {
    TL = window.TIMELINE;
    if (!TL) throw new Error('TIMELINE missing');
    stage = document.getElementById('stage');
    TL.scenes.forEach((sc, i) => {
      const def = defs.get(sc.id) || templates.get(sc.template || sc.file);
      const root = h('div', { class: 'scene', 'data-scene': sc.id, style: { zIndex: String(10 + i), display: 'none' } });
      stage.append(root);
      const ctx = makeCtx(sc);
      const entry = { sc, def, root, ctx, state: null, i };
      if (!def) {
        // visible placeholder so missing scenes are obvious in previews
        root.className += ' grid-night center';
        root.append(h('div', { style: { font: '700 64px var(--mono)', color: '#C9DF8D' } }, `[missing scene ${sc.id}]`));
      } else {
        entry.state = def.build(root, ctx) || {};
      }
      scenes.push(entry);
    });
    scenes.forEach((e, i) => { e.ctx.next = scenes[i + 1] ? scenes[i + 1].sc : null; e.ctx.prev = scenes[i - 1] ? scenes[i - 1].sc : null; });

    // persistent chrome
    subsEl = h('div', { id: 'subs' }); subEl = h('div', { class: 'sub' }); subsEl.append(subEl);
    chromeEl = h('div', { id: 'chrome' });
    chapterEl = h('div', { id: 'chapter' });
    chapterNum = h('span', { class: 'num' }); chapterLabel = h('span', { class: 'label' });
    chapterEl.append(chapterNum, chapterLabel);
    logoEl = h('div', { id: 'logo' });
    progressEl = h('div', { id: 'progress' });
    chromeEl.append(chapterEl, logoEl, progressEl);
    wipebar = h('div', { id: 'wipebar' });
    wipeEdge = h('div', { style: { position: 'absolute', left: '0px', right: '0px', height: '3px', zIndex: '960', display: 'none',
      background: 'rgba(35,134,83,.8)', boxShadow: '0 -14px 28px rgba(36,30,30,.16)' } });
    grainEl = h('div', { id: 'grain' });
    vignetteEl = h('div', { id: 'vignette' });
    vignetteOut = h('div', { id: 'vignette', style: { display: 'none' } });
    stage.append(subsEl, chromeEl, wipebar, wipeEdge, vignetteEl, vignetteOut, grainEl);
    if (/[?&]debug=1/.test(location.search)) {
      debugEl = h('div', { style: { position: 'absolute', left: '12px', top: '12px', zIndex: '999', padding: '6px 10px', borderRadius: '8px',
        background: 'rgba(255,0,90,.85)', color: '#fff', font: '700 26px/1 var(--mono)' } });
      stage.append(debugEl);
    }
    if (/[?&]nograin=1/.test(location.search)) grainEl.style.display = 'none';
    buildGrain();
  }

  function buildGrain() {
    const r = rng('grain');
    for (let k = 0; k < 6; k++) {
      const c = document.createElement('canvas'); c.width = c.height = 256;
      const g = c.getContext('2d'); const img = g.createImageData(256, 256);
      for (let i = 0; i < img.data.length; i += 4) { const v = Math.floor(r() * 255); img.data[i] = img.data[i + 1] = img.data[i + 2] = v; img.data[i + 3] = 255; }
      g.putImageData(img, 0, 0);
      grainTiles.push(c.toDataURL('image/png'));
    }
  }

  // Transition effect applied to the incoming scene container (p: 0 -> 1) and the outgoing one.
  function applyTransition(type, p, inc, out, sc) {
    const e = ease.inOutCubic(p);
    inc.style.clipPath = ''; inc.style.opacity = ''; inc.style.transform = ''; inc.style.filter = '';
    if (out) { out.style.transform = ''; out.style.opacity = ''; out.style.filter = ''; }
    wipebar.style.display = 'none';
    wipeEdge.style.display = 'none';
    switch (type) {
      case 'fade': inc.style.opacity = e.toFixed(4); break;
      case 'wipe': {
        const x = e * W;
        inc.style.clipPath = `inset(0 ${(W - x).toFixed(1)}px 0 0)`;
        if (p > 0 && p < 1) { wipebar.style.display = 'block'; wipebar.style.left = `${(x - 9).toFixed(1)}px`; wipebar.style.background = sc.theme === 'light' ? 'var(--green)' : 'var(--lime)'; }
        break;
      }
      case 'wipe-up': {
        const y = e * H;
        inc.style.clipPath = `inset(${(H - y).toFixed(1)}px 0 0 0)`;
        // a visible sheet edge so the page turn reads as paper, not as a mask (both pages are the same grid paper)
        if (p > 0 && p < 1) {
          wipeEdge.style.display = 'block';
          wipeEdge.style.top = `${(H - y - 1.5).toFixed(1)}px`;
        }
        break;
      }
      case 'iris': {
        const cx = (sc.transition && sc.transition.cx) || W / 2, cy = (sc.transition && sc.transition.cy) || H / 2;
        const R = Math.hypot(Math.max(cx, W - cx), Math.max(cy, H - cy));
        inc.style.clipPath = `circle(${(ease.inOutQuart(p) * R).toFixed(1)}px at ${cx}px ${cy}px)`;
        break;
      }
      case 'push': {
        inc.style.transform = `translate(${((1 - e) * W).toFixed(1)}px,0px)`;
        if (out) out.style.transform = `translate(${(-e * W * 0.35).toFixed(1)}px,0px)`;
        if (out) out.style.opacity = (1 - e * 0.6).toFixed(3);
        break;
      }
      case 'zoom': {
        inc.style.opacity = ease.outCubic(p).toFixed(4);
        inc.style.transform = `scale(${lerp(1.12, 1, ease.outCubic(p)).toFixed(4)})`;
        if (out) { out.style.transform = `scale(${lerp(1, 0.92, e).toFixed(4)})`; }
        break;
      }
      case 'blur': {
        inc.style.opacity = e.toFixed(4);
        if (out) out.style.filter = `blur(${(e * 16).toFixed(1)}px)`;
        break;
      }
      default: break; // 'cut' or scene-handled
    }
  }

  let lastChapter = null;
  async function seek(t) {
    for (let pass = 0; pass < 4; pass++) {
      pending.clear();
      renderAt(t);
      if (!pending.size) break;
      await Promise.all([...pending]);
    }
  }

  function renderAt(t) {
    // which scenes are visible: current scene + previous one during the current scene's transition-in
    let cur = scenes.length - 1;
    for (let i = 0; i < scenes.length; i++) { if (t < scenes[i].sc.start + scenes[i].sc.dur) { cur = i; break; } }
    const curE = scenes[cur];
    const tr = curE.sc.transition || { type: 'cut', dur: 0 };
    const tIn = t - curE.sc.start;
    const inTransition = cur > 0 && tr.type !== 'cut' && tr.dur > 0 && tIn < tr.dur;
    const visible = new Set([cur]);
    if (inTransition) visible.add(cur - 1);
    // scenes can ask to keep the previous scene alive longer (e.g. shared-element morphs)
    scenes.forEach((e, i) => {
      const show = visible.has(i);
      const disp = show ? 'block' : 'none';
      if (e.root.style.display !== disp) e.root.style.display = disp;
      if (!show) return;
      if (e.def) {
        try { e.def.render(e.state, t - e.sc.start, e.ctx); }
        catch (err) { console.error(`render ${e.sc.id} @${t}`, err); throw err; }
      }
    });
    if (inTransition) applyTransition(tr.type, clamp(tIn / tr.dur), curE.root, scenes[cur - 1].root, curE.sc);
    else { applyTransition('cut', 1, curE.root, cur > 0 ? scenes[cur - 1].root : null, curE.sc); }

    // chrome: chapter label, logo theme, progress, subtitles
    const theme = curE.sc.theme || 'dark';
    const ch = (TL.chapters || []).find(c => t >= c.start && t < c.end);
    const chromeOff = e => !!e && (e.sc.chrome === false || (e.def && e.def.chrome === false));
    const prevE = cur > 0 ? scenes[cur - 1] : null;
    // chrome fades out over the first 0.35 s of a chrome-off scene, and back in after one
    let chromeA = 1;
    if (chromeOff(curE)) chromeA = prevE && !chromeOff(prevE) ? 1 - prog(tIn, 0, 0.35, ease.inOutCubic) : 0;
    else if (prevE && chromeOff(prevE)) chromeA = prog(tIn, 0, 0.35, ease.inOutCubic);
    const hideChrome = chromeA <= 0.001;
    chapterEl.style.visibility = ch && !hideChrome ? 'visible' : 'hidden';
    if (ch) {
      if (lastChapter !== ch.id) { chapterNum.textContent = ch.num; chapterLabel.textContent = ch.label; lastChapter = ch.id; }
      const a = prog(t, ch.start + 0.2, 0.5) * (1 - prog(t, ch.end - 0.4, 0.4)) * chromeA;
      chapterEl.style.opacity = a.toFixed(3);
      chapterEl.style.transform = `translate(${((1 - prog(t, ch.start + 0.2, 0.6, ease.outQuint)) * -30).toFixed(1)}px,0px)`;
    }
    // A horizontal wipe between a dark and a light page: chrome follows the moving edge, not the first frame.
    const prevTheme = cur > 0 ? (scenes[cur - 1].sc.theme || 'dark') : theme;
    const splitWipe = inTransition && tr.type === 'wipe' && prevTheme !== theme;
    const edgeX = splitWipe ? ease.inOutCubic(clamp(tIn / tr.dur)) * W : W;
    const logoTheme = splitWipe && edgeX < 1700 ? prevTheme : theme;
    const logoSvg = logoTheme === 'light' ? window.LOGO_LIGHT : window.LOGO_DARK;
    if (logoEl.dataset.theme !== logoTheme && logoSvg) { logoEl.innerHTML = logoSvg; logoEl.dataset.theme = logoTheme; }
    if (ch) { const labelTheme = splitWipe && edgeX < 320 ? prevTheme : theme; chapterLabel.style.color = labelTheme === 'light' ? 'var(--ink)' : 'var(--snow)'; }
    logoEl.style.visibility = hideChrome ? 'hidden' : 'visible';
    logoEl.style.opacity = (0.9 * chromeA).toFixed(3);
    progressEl.style.opacity = chromeA.toFixed(3);
    const vig = e => ((e.sc.theme || 'dark') === 'light' ? 0.12 : (e.sc.vignette != null ? e.sc.vignette : 1));
    if (splitWipe) {
      // each page keeps its own vignette strength on its side of the wipe edge
      vignetteEl.style.opacity = vig(curE).toFixed(3);
      vignetteEl.style.clipPath = `inset(0 ${(W - edgeX).toFixed(1)}px 0 0)`;
      vignetteOut.style.display = 'block';
      vignetteOut.style.opacity = vig(scenes[cur - 1]).toFixed(3);
      vignetteOut.style.clipPath = `inset(0 0 0 ${edgeX.toFixed(1)}px)`;
    } else {
      const vNow = inTransition ? lerp(vig(scenes[cur - 1]), vig(curE), ease.inOutCubic(clamp(tIn / tr.dur))) : vig(curE);
      vignetteEl.style.opacity = vNow.toFixed(3);
      vignetteEl.style.clipPath = '';
      vignetteOut.style.display = 'none';
    }
    progressEl.style.width = `${((t / TL.duration) * W).toFixed(1)}px`;
    const pc = th => (th === 'light' ? '#238653' : '#C9DF8D');
    progressEl.style.background = splitWipe
      ? `linear-gradient(90deg, ${pc(theme)} 0px, ${pc(theme)} ${edgeX.toFixed(1)}px, ${pc(prevTheme)} ${edgeX.toFixed(1)}px)`
      : pc(theme);
    progressEl.style.visibility = hideChrome ? 'hidden' : 'visible';

    let sub = null;
    for (const l of TL.lines) {
      if (t < l.start - 0.05 || t > l.end + 0.6) continue;
      for (const sb of l.subs || []) if (t >= sb.start && t < sb.end) { sub = sb; break; }
      if (sub) break;
    }
    const subsOff = curE.sc.subs === false || NOSUBS;
    if (sub && !subsOff) {
      if (subEl.textContent !== sub.text) subEl.textContent = sub.text;
      subsEl.style.visibility = 'visible';
    } else subsEl.style.visibility = 'hidden';

    grainEl.style.backgroundImage = `url(${grainTiles[Math.floor(t * TL.fps) % grainTiles.length]})`;
    if (debugEl) debugEl.textContent = `t=${t.toFixed(2)}s  ${curE.sc.id} @${tIn.toFixed(2)}s`;
  }

  // SFX events from all scenes, in absolute seconds
  function events() {
    const out = [];
    scenes.forEach(e => {
      const tr = e.sc.transition;
      if (tr && tr.type !== 'cut' && tr.sfx !== false && e.i > 0) out.push({ t: e.sc.start, type: tr.sfx || 'whoosh', gain: 0.5, scene: e.sc.id });
      if (e.def && e.def.events) for (const ev of e.def.events(e.ctx) || []) out.push({ ...ev, t: e.sc.start + ev.t, scene: e.sc.id });
    });
    return out.sort((a, b) => a.t - b.t);
  }

  async function boot() {
    const families = ['900 64px NSC', '400 64px NSC', '700 64px NSerif', '64px Smiley', '700 64px Grotesk', '500 64px Inter', '500 64px Mono'];
    await Promise.all(families.map(f => document.fonts.load(f, '永Aa0')));
    await document.fonts.ready;
    init();
    window.__ready = true;
  }

  window.M = M;
  // Replace {{KEY}} placeholders with production numbers from window.STATS (tools/stats.py)
  const fill = str => String(str).replace(/\{\{(\w+)\}\}/g, (m, k) => (window.STATS && window.STATS[k] != null ? window.STATS[k] : m));
  window.E = { W, H, h, s, tf, chars, typed, image, setImg, bgImg, clipUrl, clipInfo, Scene, fill };
  window.Scene = Scene;
  window.__seek = seek;
  window.__events = events;
  window.__duration = () => TL.duration;
  window.__boot = boot;
})();
