#!/usr/bin/env python3
"""Extract clip segments from case videos into JPEG frame sequences the engine can seek exactly.

script/clips.json: { "<clipId>": {"src": "assets/cases/<case>.mp4", "start": 3.2, "end": 9.0,
                                  "width": 1280, "fps": 30, "crop": "iw:ih*0.8:0:ih*0.1" (optional ffmpeg crop expr)} }
Writes src/media/<clipId>/f00001.jpg ... and src/media/manifest.js (window.MEDIA). Skips clips whose frames exist
with the same parameters (hash stored in src/media/<clipId>/.params).
"""
import json, os, subprocess, sys, hashlib, shutil
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
spec = json.load(open(os.path.join(ROOT, 'script', 'clips.json')))
media = {}
only = set(sys.argv[1:])
for cid, c in spec.items():
    out = os.path.join(ROOT, 'src', 'media', cid)
    fps = c.get('fps', 30)
    params = json.dumps(c, sort_keys=True)
    ph = hashlib.sha1(params.encode()).hexdigest()
    pfile = os.path.join(out, '.params')
    fresh = os.path.exists(pfile) and open(pfile).read() == ph
    if (not fresh) and (not only or cid in only):
        shutil.rmtree(out, ignore_errors=True)
        os.makedirs(out, exist_ok=True)
        vf = []
        if c.get('crop'):
            vf.append(f"crop={c['crop']}")
        vf.append(f"fps={fps}")
        vf.append(f"scale={c.get('width', 1280)}:-2:flags=lanczos")
        cmd = ['ffmpeg', '-v', 'error', '-y', '-ss', str(c['start']), '-to', str(c['end']), '-i', os.path.join(ROOT, c['src']),
               '-vf', ','.join(vf), '-q:v', str(c.get('q', 3)), os.path.join(out, 'f%05d.jpg')]
        subprocess.run(cmd, check=True)
        open(pfile, 'w').write(ph)
    frames = sorted(f for f in os.listdir(out) if f.endswith('.jpg')) if os.path.isdir(out) else []
    if not frames:
        print(f'WARN no frames for {cid}', file=sys.stderr)
        continue
    w, h = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'stream=width,height', '-of', 'csv=p=0', os.path.join(out, frames[0])],
                          capture_output=True, text=True, check=True).stdout.strip().split(',')[:2]
    media[cid] = {'fps': fps, 'frames': len(frames), 'w': int(w), 'h': int(h), 'dir': f'media/{cid}', 'src': c['src'],
                  'srcStart': c['start'], 'srcEnd': c['end'], 'case': c.get('case'), 'author': c.get('author')}
    print(f"{cid}: {len(frames)} frames {w}x{h}")
with open(os.path.join(ROOT, 'src', 'media', 'manifest.js'), 'w') as f:
    f.write('// Generated by tools/extract_clips.py from script/clips.json\nwindow.MEDIA = ' + json.dumps(media, ensure_ascii=False, indent=1) + ';\n')
