#!/usr/bin/env python3
"""Real production numbers for the on-screen "how this film was made" stats -> src/stats.js (window.STATS).
Placeholders like {{FRAMES}} in scene text are filled by E.fill() from these values."""
import glob, json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tl = json.load(open(os.path.join(ROOT, 'audio', 'timeline.json')))
def lines(paths):
    n = 0
    for p in paths:
        with open(p, encoding='utf-8', errors='ignore') as f:
            n += sum(1 for ln in f if ln.strip())
    return n
scene_files = glob.glob(os.path.join(ROOT, 'src', 'scenes', '*.js'))
scene_files = [p for p in scene_files if not os.path.basename(p).startswith('_')]
engine_files = glob.glob(os.path.join(ROOT, 'src', 'lib', '*.js'))
engine_files = [p for p in engine_files if not p.endswith('logos.js')] + [os.path.join(ROOT, 'src', 'main.js')]
PIPELINE = ['browser.mjs', 'still.mjs', 'render.mjs', 'events.mjs', 'build_timeline.py', 'extract_clips.py', 'music.py', 'mix.py',
            'finalize.sh', 'build.sh', 'stats.py', 'asr_check.py']
tool_files = [os.path.join(ROOT, 'tools', f) for f in PIPELINE if os.path.exists(os.path.join(ROOT, 'tools', f))]
render_json = os.path.join(ROOT, 'render', 'video.render.json')
render_min = None
if os.path.exists(render_json):
    r = json.load(open(render_json))
    if r.get('scale', 1) == 1:
        render_min = round(r['seconds'] / 60, 1)
clips = json.load(open(os.path.join(ROOT, 'script', 'clips.json')))
stats = {
    'FRAMES': f"{round(tl['duration'] * tl['fps']):,}",
    'SECONDS': f"{tl['duration']:.0f}",
    'SCENES': str(len(tl['scenes'])),
    'LINES': str(len(tl['lines'])),
    'CODE_LINES': f"{lines(scene_files + engine_files + tool_files):,}",
    'SCENE_CODE_LINES': f"{lines(scene_files):,}",
    'MUSIC_CODE_LINES': f"{lines([os.path.join(ROOT, 'tools', 'music.py')]):,}",
    'RENDER_MIN': (f"{render_min:g}" if render_min else None),  # unknown until a full render exists: leave {{RENDER_MIN}} visible
    'CLIPS': str(len(clips)),
    'WORKERS': '6',
    'FPS': str(tl['fps']),
}
stats = {k: v for k, v in stats.items() if v is not None}
with open(os.path.join(ROOT, 'src', 'stats.js'), 'w') as f:
    f.write('// Generated by tools/stats.py\nwindow.STATS = ' + json.dumps(stats, ensure_ascii=False, indent=1) + ';\n')
print(json.dumps(stats, ensure_ascii=False))
