// Generated by tools/stats.py
window.STATS = {
 "FRAMES": "8,130",
 "SECONDS": "271",
 "SCENES": "23",
 "LINES": "58",
 "CODE_LINES": "11,694",
 "SCENE_CODE_LINES": "9,561",
 "MUSIC_CODE_LINES": "265",
 "RENDER_MIN": "6",
 "CLIPS": "26",
 "WORKERS": "6",
 "FPS": "30"
};
