// Generated by tools/build_timeline.py from script/narration.json. Do not edit by hand.
window.TIMELINE = {
 "fps": 30,
 "duration": 271.0,
 "bpm": 120,
 "voice": "zh-CN-YunxiNeural",
 "scenes": [
  {
   "id": "s00_cover",
   "file": "s00_cover",
   "template": null,
   "start": 0.0,
   "dur": 2.0,
   "theme": "dark",
   "chapter": "c0",
   "transition": {
    "type": "cut",
    "dur": 0
   },
   "subs": false,
   "chrome": false,
   "music": {
    "energy": 3
   },
   "data": {}
  },
  {
   "id": "s01_cold",
   "file": "s01_cold",
   "template": null,
   "start": 2.0,
   "dur": 8.0,
   "theme": "dark",
   "chapter": "c0",
   "transition": {
    "type": "cut",
    "dur": 0
   },
   "subs": true,
   "chrome": false,
   "music": {
    "energy": 3
   },
   "data": {}
  },
  {
   "id": "s02_title",
   "file": "s02_title",
   "template": null,
   "start": 10.0,
   "dur": 8.5,
   "theme": "dark",
   "chapter": "c0",
   "transition": {
    "type": "cut",
    "dur": 0
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 3
   },
   "data": {}
  },
  {
   "id": "s03_text",
   "file": "s03_text",
   "template": null,
   "start": 18.5,
   "dur": 10.5,
   "theme": "dark",
   "chapter": "c1",
   "transition": {
    "type": "wipe",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s04_render",
   "file": "s04_render",
   "template": null,
   "start": 29.0,
   "dur": 18.0,
   "theme": "dark",
   "chapter": "c1",
   "transition": {
    "type": "zoom",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s05_wall",
   "file": "s05_wall",
   "template": null,
   "start": 47.0,
   "dur": 11.0,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "wipe",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {}
  },
  {
   "id": "s06_c1",
   "file": "case",
   "template": "case",
   "start": 58.0,
   "dur": 11.5,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "zoom",
    "dur": 0.6,
    "sfx": false
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {
    "index": 1,
    "total": 8,
    "aspect": "1:1",
    "author": "@twoclipping",
    "work": "无缝 UI 形变",
    "tagline": "路线：代码生成与渲染",
    "secret": "一个形状贯穿全片",
    "points": [
     "14 秒一镜到底，一刀没剪"
    ],
    "takeaway": "先定贯穿对象，再让变化踩上节拍",
    "caveat": "作者自述：全片是代码，未用 AE",
    "clips": [
     {
      "id": "c1-006-morph"
     },
     {
      "id": "c1-006-tail"
     }
    ],
    "cues": {
     "secret": [
      "s06_c1.1",
      "一个"
     ],
     "points": [
      [
       "s06_c1.2",
       "14"
      ]
     ],
     "takeaway": "s06_c1.3"
    },
    "layout": "A",
    "proof": {
     "type": "chain",
     "dir": "v",
     "pos": "left",
     "items": [
      {
       "label": "按钮",
       "clip": 0,
       "t": 0,
       "say": [
        "s06_c1.2",
        "按钮"
       ]
      },
      {
       "label": "播放器",
       "clip": 0,
       "t": 1.5
      },
      {
       "label": "开关",
       "clip": 0,
       "t": 5.3
      },
      {
       "label": "图表",
       "clip": 0,
       "t": 7.4,
       "say": [
        "s06_c1.2",
        "图表"
       ]
      },
      {
       "label": "命令面板",
       "clip": 1,
       "t": 0.65
      }
     ]
    }
   }
  },
  {
   "id": "s07_c2",
   "file": "case",
   "template": "case",
   "start": 69.5,
   "dur": 10.5,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "push",
    "dur": 0.6,
    "sfx": false
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {
    "index": 2,
    "total": 8,
    "aspect": "16:9",
    "author": "@morpheusdv",
    "work": "《The First Spark》",
    "tagline": "路线：代码生成与渲染",
    "secret": "暖色只留给高潮",
    "points": [
     "除了这 9 秒暖光，全片只有纸色和墨色"
    ],
    "takeaway": "风格拆成能检查的规则",
    "caveat": "作者自述纯 JS；提示另附参考图",
    "clips": [
     {
      "id": "c2-060-tree",
      "dur": 4.4
     },
     {
      "id": "c2-060-light"
     }
    ],
    "cues": {
     "secret": [
      "s07_c2.1",
      "暖色"
     ],
     "points": [
      [
       "s07_c2.2",
       "全片"
      ]
     ],
     "takeaway": "s07_c2.3"
    },
    "layout": "B",
    "proof": {
     "type": "film",
     "total": 60,
     "warm": [
      46.5,
      55.5
     ],
     "label": "全片 60 秒",
     "warmLabel": [
      "暖光",
      "9 秒"
     ],
     "cues": {
      "total": [
       "s07_c2.2",
       "60 秒"
      ],
      "warm": [
       "s07_c2.2",
       "暖"
      ],
      "nine": [
       "s07_c2.2",
       "9 秒"
      ]
     }
    },
    "shrink": "s07_c2.2"
   }
  },
  {
   "id": "s08_c3",
   "file": "case",
   "template": "case",
   "start": 80.0,
   "dur": 10.0,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "push",
    "dur": 0.6,
    "sfx": false
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {
    "index": 3,
    "total": 8,
    "aspect": "16:9",
    "author": "@kimmonismus",
    "work": "AI 历史短片",
    "tagline": "路线：代码渲染＋语音合成",
    "secret": "画面、旁白、配乐分层做",
    "points": [
     "每层单独改，再沿一条时间轴合成"
    ],
    "takeaway": "画面、旁白、配乐各管一层，对齐一条时间轴",
    "caveat": "工具栈为作者自述，工程未公开",
    "clips": [
     {
      "id": "c3-0962-web"
     },
     {
      "id": "c3-0962-burst"
     }
    ],
    "cues": {
     "secret": [
      "s08_c3.1",
      "画面"
     ],
     "points": [
      [
       "s08_c3.1",
       "每"
      ]
     ],
     "takeaway": "s08_c3.2",
     "caveat": [
      "s08_c3.1",
      "每"
     ]
    },
    "layout": "A",
    "proof": {
     "type": "lanes",
     "label": "一条时间轴",
     "note": "示意",
     "lanes": [
      {
       "label": "画面",
       "cue": [
        "s08_c3.1",
        "画面"
       ]
      },
      {
       "label": "旁白",
       "cue": [
        "s08_c3.1",
        "旁白"
       ]
      },
      {
       "label": "配乐",
       "cue": [
        "s08_c3.1",
        "配乐"
       ]
      }
     ],
     "edits": [
      [
       "s08_c3.1",
       "每"
      ],
      [
       "s08_c3.1",
       "层",
       1
      ],
      [
       "s08_c3.1",
       "单"
      ]
     ],
     "align": [
      "s08_c3.2",
      "对"
     ]
    }
   }
  },
  {
   "id": "s09_c4",
   "file": "case",
   "template": "case",
   "start": 90.0,
   "dur": 13.0,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "push",
    "dur": 0.6,
    "sfx": false
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {
    "index": 4,
    "total": 8,
    "aspect": "16:9",
    "author": "@WinterArc2125",
    "work": "奥斯特里茨战役",
    "tagline": "路线：代码渲染＋开放数据",
    "secret": "用真实数据当约束",
    "points": [
     "地形取自公开海拔数据，纵向放大 3 倍"
    ],
    "takeaway": "先找真实数据，每个镜头写清依据和用意",
    "caveat": "作者自述：构建 90 分钟，渲染 4 小时",
    "clips": [
     {
      "id": "c4-1377-relief"
     },
     {
      "id": "c4-1377-arrows"
     },
     {
      "id": "c4-1377-sun"
     }
    ],
    "cues": {
     "secret": [
      "s09_c4.1",
      "真实"
     ],
     "points": [
      [
       "s09_c4.2",
       "海拔"
      ]
     ],
     "takeaway": "s09_c4.3"
    },
    "layout": "B",
    "proof": {
     "type": "chain",
     "items": [
      {
       "label": "地形数据",
       "clip": 0,
       "t": 1.6
      },
      {
       "label": "地图",
       "sub": "讲移动",
       "cue": [
        "s09_c4.2",
        "地图"
       ]
      },
      {
       "label": "地面镜头",
       "sub": "给情绪",
       "cue": [
        "s09_c4.2",
        "地面"
       ]
      }
     ]
    },
    "shrink": "s09_c4.2"
   }
  },
  {
   "id": "s10_c5",
   "file": "case",
   "template": "case",
   "start": 103.0,
   "dur": 13.5,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "push",
    "dur": 0.6,
    "sfx": false
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {
    "index": 5,
    "total": 8,
    "aspect": "16:9",
    "author": "@aiwarts",
    "work": "网站产品宣传片",
    "tagline": "路线：代码＋网站已有素材",
    "secret": "用户怎么点，镜头怎么走",
    "points": [],
    "takeaway": "每个卖点，配一段真实界面",
    "caveat": "网页卡片里是他人作品，非 Opus 生成",
    "clips": [
     {
      "id": "c5-072-brand",
      "dur": 5.92
     },
     {
      "id": "c5-072-home",
      "dur": 1.0,
      "credit": "right"
     },
     {
      "id": "c5-072-search"
     },
     {
      "id": "c5-072-prompt"
     }
    ],
    "cues": {
     "secret": [
      "s10_c5.2",
      "用户"
     ],
     "takeaway": "s10_c5.3",
     "caveat": "s10_c5.2"
    },
    "layout": "A",
    "proof": {
     "type": "chain",
     "items": [
      {
       "label": "首页",
       "clip": 1
      },
      {
       "label": "搜索",
       "clip": 2
      },
      {
       "label": "复制提示词",
       "clip": 3
      }
     ]
    },
    "bridge": {
     "text": [
      "后 4 招",
      "画面里有现成素材或别的模型"
     ],
     "line": "s10_c5.1",
     "mark": {
      "box": [
       0.05,
       0.682,
       0.94,
       0.86
      ],
      "at": [
       "s10_c5.1",
       "现成"
      ],
      "label": "他人作品",
      "push": 0.04,
      "pushFrom": {
       "clip": 0,
       "t": 1.7
      }
     }
    },
    "tint": {
     "from": 5,
     "at": [
      "s10_c5.1",
      "后"
     ]
    }
   }
  },
  {
   "id": "s11_c6",
   "file": "case",
   "template": "case",
   "start": 116.5,
   "dur": 12.5,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "push",
    "dur": 0.6,
    "sfx": false
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {
    "index": 6,
    "total": 8,
    "aspect": "9:16",
    "author": "@yoshifujidesign",
    "work": "手机 3D 概念片",
    "tagline": "路线：已有 3D 数据＋多版风格",
    "secret": "产品不动，只换演出",
    "points": [],
    "takeaway": "模型锁死，只改镜头、光线和配色",
    "caveat": "片中参数为虚构；渲染工具未公开",
    "clips": [
     {
      "id": "c6-054-line",
      "from": 0.8
     },
     {
      "id": "c6-054-render"
     }
    ],
    "cues": {
     "secret": [
      "s11_c6.1",
      "产品"
     ],
     "takeaway": "s11_c6.3",
     "caveat": "s11_c6.2"
    },
    "layout": "B",
    "trio": {
     "at": [
      "s11_c6.2",
      "同"
     ],
     "labels": [
      "版本 1 · 线稿",
      "版本 1 · 渲染",
      "版本 2 · 插画"
     ],
     "side": [
      {
       "id": "c6-054-line",
       "from": 0.8,
       "loop": "pingpong",
       "loopFrom": 1.4
      },
      {
       "id": "c6-054b-plume",
       "from": 0
      }
     ]
    },
    "tint": {
     "from": 5
    },
    "shrink": {
     "clip": 1,
     "t": 2.4
    }
   }
  },
  {
   "id": "s12_c7",
   "file": "case",
   "template": "case",
   "start": 129.0,
   "dur": 14.0,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "push",
    "dur": 0.6,
    "sfx": false
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {
    "index": 7,
    "total": 8,
    "aspect": "16:9",
    "author": "@aicreataro",
    "work": "舞蹈骨架 MV",
    "tagline": "路线：Opus 操作 AE＋生成素材",
    "secret": "让动作驱动特效",
    "points": [
     "先给观众看骨架数据，再看效果"
    ],
    "takeaway": "别贪多：挑两三个动作，各绑一种效果",
    "caveat": "据作者：舞者和歌由生成模型制作",
    "clips": [
     {
      "id": "c7-2348-hikare",
      "dur": 1.9
     },
     {
      "id": "c7-2348-skel"
     },
     {
      "id": "c7-2348-lyric",
      "dur": 6.0
     },
     {
      "id": "c7-2348-hikare",
      "from": 1.9,
      "dur": 3.6
     }
    ],
    "cues": {
     "secret": [
      "s12_c7.1",
      "动作"
     ],
     "points": [
      [
       "s12_c7.2",
       "骨架"
      ]
     ],
     "takeaway": "s12_c7.3"
    },
    "layout": "A",
    "proof": {
     "type": "chain",
     "items": [
      {
       "label": "骨架坐标",
       "clip": 1,
       "t": 0
      },
      {
       "label": "落地",
       "sub": "炸光",
       "clip": 1,
       "t": 0.5
      },
      {
       "label": "举手",
       "sub": "歌词",
       "clip": 2,
       "t": 1.8,
       "sep": "＋"
      },
      {
       "label": "握拳",
       "sub": "锁定",
       "clip": 3,
       "t": 2.4,
       "sep": "＋"
      }
     ]
    },
    "tint": {
     "from": 5
    },
    "shrink": [
     "s12_c7.2",
     "作者"
    ],
    "capTop": 100
   }
  },
  {
   "id": "s13_c8",
   "file": "case",
   "template": "case",
   "start": 143.0,
   "dur": 13.5,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "push",
    "dur": 0.6,
    "sfx": false
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 2
   },
   "data": {
    "index": 8,
    "total": 8,
    "aspect": "16:9",
    "author": "@KanaWorks_AI",
    "work": "五幕舞台短片",
    "tagline": "路线：多模型制作",
    "secret": "多模型各管一段",
    "points": [
     "换景藏在幕布后面，没有硬切"
    ],
    "takeaway": "分工时，每个镜头写清谁来做、怎样算合格",
    "caveat": "分工为作者自述，不是模型排名",
    "clips": [
     {
      "id": "c8-133-stage"
     }
    ],
    "cues": {
     "secret": [
      "s13_c8.1",
      "多个"
     ],
     "points": [
      {
       "clip": 0,
       "t": 4.7
      }
     ],
     "takeaway": "s13_c8.3"
    },
    "layout": "A",
    "kenBurns": false,
    "proof": {
     "type": "chain",
     "sep": "",
     "items": [
      {
       "label": "Opus",
       "sub": "统筹",
       "cue": [
        "s13_c8.2",
        "Opus"
       ]
      },
      {
       "label": "Seedance",
       "sub": "动作",
       "cue": [
        "s13_c8.2",
        "人物"
       ]
      },
      {
       "label": "GPT Image",
       "sub": "布景",
       "cue": [
        "s13_c8.2",
        "布景"
       ]
      }
     ]
    },
    "tint": {
     "from": 5
    },
    "shrink": "s13_c8.2"
   }
  },
  {
   "id": "s14_formula",
   "file": "s14_formula",
   "template": null,
   "start": 156.5,
   "dur": 13.5,
   "theme": "dark",
   "chapter": "c2",
   "transition": {
    "type": "iris",
    "dur": 0.7
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s15_env",
   "file": "s15_env",
   "template": null,
   "start": 170.0,
   "dur": 13.0,
   "theme": "light",
   "chapter": "c3",
   "transition": {
    "type": "wipe",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s16_routes",
   "file": "s16_routes",
   "template": null,
   "start": 183.0,
   "dur": 18.0,
   "theme": "light",
   "chapter": "c3",
   "transition": {
    "type": "wipe-up",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s17_prompt",
   "file": "s17_prompt",
   "template": null,
   "start": 201.0,
   "dur": 12.5,
   "theme": "light",
   "chapter": "c3",
   "transition": {
    "type": "wipe-up",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s18_sample",
   "file": "s18_sample",
   "template": null,
   "start": 213.5,
   "dur": 7.0,
   "theme": "light",
   "chapter": "c3",
   "transition": {
    "type": "wipe-up",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s19_feedback",
   "file": "s19_feedback",
   "template": null,
   "start": 220.5,
   "dur": 12.0,
   "theme": "light",
   "chapter": "c3",
   "transition": {
    "type": "wipe-up",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s20_ship",
   "file": "s20_ship",
   "template": null,
   "start": 232.5,
   "dur": 15.5,
   "theme": "light",
   "chapter": "c3",
   "transition": {
    "type": "wipe-up",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 1
   },
   "data": {}
  },
  {
   "id": "s21_meta",
   "file": "s21_meta",
   "template": null,
   "start": 248.0,
   "dur": 14.5,
   "theme": "dark",
   "chapter": "c4",
   "transition": {
    "type": "wipe",
    "dur": 0.6
   },
   "subs": true,
   "chrome": true,
   "music": {
    "energy": 3
   },
   "data": {}
  },
  {
   "id": "s22_end",
   "file": "s22_end",
   "template": null,
   "start": 262.5,
   "dur": 8.5,
   "theme": "dark",
   "chapter": "c4",
   "transition": {
    "type": "iris",
    "dur": 0.7,
    "cx": 960,
    "cy": 540
   },
   "subs": true,
   "chrome": false,
   "music": {
    "energy": 2
   },
   "data": {}
  }
 ],
 "lines": [
  {
   "id": "s01_cold.1",
   "scene": "s01_cold",
   "text": "最近有一批视频，没有一帧是拍出来的。",
   "start": 2.25,
   "end": 4.95,
   "words": [
    {
     "w": "最近",
     "start": 2.25,
     "end": 2.545
    },
    {
     "w": "有",
     "start": 2.568,
     "end": 2.663
    },
    {
     "w": "一批",
     "start": 2.663,
     "end": 2.828
    },
    {
     "w": "视频",
     "start": 2.84,
     "end": 3.394
    },
    {
     "w": "没有",
     "start": 3.712,
     "end": 3.948
    },
    {
     "w": "一",
     "start": 3.96,
     "end": 4.09
    },
    {
     "w": "帧",
     "start": 4.09,
     "end": 4.29
    },
    {
     "w": "是",
     "start": 4.29,
     "end": 4.384
    },
    {
     "w": "拍",
     "start": 4.396,
     "end": 4.573
    },
    {
     "w": "出来",
     "start": 4.573,
     "end": 4.762
    },
    {
     "w": "的",
     "start": 4.762,
     "end": 4.95
    }
   ],
   "subs": [
    {
     "text": "最近有一批视频，没有一帧是拍出来的",
     "start": 2.25,
     "end": 5.1
    }
   ]
  },
  {
   "id": "s01_cold.2",
   "scene": "s01_cold",
   "text": "也不是 AI 一键生成的。",
   "start": 5.17,
   "end": 7.01,
   "words": [
    {
     "w": "也",
     "start": 5.17,
     "end": 5.312
    },
    {
     "w": "不是",
     "start": 5.312,
     "end": 5.748
    },
    {
     "w": "AI",
     "start": 5.843,
     "end": 6.255
    },
    {
     "w": "一键",
     "start": 6.267,
     "end": 6.479
    },
    {
     "w": "生成",
     "start": 6.491,
     "end": 6.845
    },
    {
     "w": "的",
     "start": 6.845,
     "end": 7.01
    }
   ],
   "subs": [
    {
     "text": "也不是 AI 一键生成的",
     "start": 5.17,
     "end": 7.16
    }
   ]
  },
  {
   "id": "s01_cold.3",
   "scene": "s01_cold",
   "text": "每一帧，都是代码。",
   "start": 8.0,
   "end": 9.616,
   "words": [
    {
     "w": "每",
     "start": 8.0,
     "end": 8.236
    },
    {
     "w": "一",
     "start": 8.236,
     "end": 8.366
    },
    {
     "w": "帧",
     "start": 8.366,
     "end": 8.66
    },
    {
     "w": "都是",
     "start": 9.002,
     "end": 9.238
    },
    {
     "w": "代码",
     "start": 9.25,
     "end": 9.616
    }
   ],
   "subs": [
    {
     "text": "每一帧，都是代码",
     "start": 8.0,
     "end": 9.766
    }
   ]
  },
  {
   "id": "s02_title.1",
   "scene": "s02_title",
   "text": "包括你现在看到的这一帧。",
   "start": 10.25,
   "end": 11.948,
   "words": [
    {
     "w": "包括",
     "start": 10.25,
     "end": 10.59
    },
    {
     "w": "你",
     "start": 10.603,
     "end": 10.726
    },
    {
     "w": "现在",
     "start": 10.726,
     "end": 11.024
    },
    {
     "w": "看到",
     "start": 11.038,
     "end": 11.31
    },
    {
     "w": "的",
     "start": 11.31,
     "end": 11.378
    },
    {
     "w": "这",
     "start": 11.405,
     "end": 11.514
    },
    {
     "w": "一",
     "start": 11.514,
     "end": 11.609
    },
    {
     "w": "帧",
     "start": 11.609,
     "end": 11.948
    }
   ],
   "subs": [
    {
     "text": "包括你现在看到的这一帧",
     "start": 10.25,
     "end": 12.098
    }
   ]
  },
  {
   "id": "s02_title.2",
   "scene": "s02_title",
   "text": "用 Opus 5.5 做的视频，为什么这么炫？小白怎么做？一次讲明白。",
   "start": 12.068,
   "end": 17.938,
   "words": [
    {
     "w": "用",
     "start": 12.068,
     "end": 12.351
    },
    {
     "w": "Opus",
     "start": 12.375,
     "end": 12.965
    },
    {
     "w": "5.5",
     "start": 12.988,
     "end": 13.377
    },
    {
     "w": "做",
     "start": 13.377,
     "end": 13.495
    },
    {
     "w": "的",
     "start": 13.495,
     "end": 13.554
    },
    {
     "w": "视频",
     "start": 13.566,
     "end": 14.049
    },
    {
     "w": "为什么",
     "start": 14.25,
     "end": 14.58
    },
    {
     "w": "这么",
     "start": 14.592,
     "end": 14.745
    },
    {
     "w": "炫",
     "start": 14.745,
     "end": 15.028
    },
    {
     "w": "小白",
     "start": 15.556,
     "end": 15.969
    },
    {
     "w": "怎么",
     "start": 15.981,
     "end": 16.134
    },
    {
     "w": "做",
     "start": 16.134,
     "end": 16.441
    },
    {
     "w": "一次",
     "start": 16.971,
     "end": 17.254
    },
    {
     "w": "讲",
     "start": 17.266,
     "end": 17.431
    },
    {
     "w": "明白",
     "start": 17.431,
     "end": 17.938
    }
   ],
   "subs": [
    {
     "text": "用 Opus 5.5 做的视频，为什么这么炫？",
     "start": 12.068,
     "end": 15.556
    },
    {
     "text": "小白怎么做？",
     "start": 15.556,
     "end": 16.971
    },
    {
     "text": "一次讲明白",
     "start": 16.971,
     "end": 18.088
    }
   ]
  },
  {
   "id": "s03_text.1",
   "scene": "s03_text",
   "text": "先看原理：Opus 5.5 只输出文字，不直接出视频。",
   "start": 18.98,
   "end": 23.166,
   "words": [
    {
     "w": "先",
     "start": 18.98,
     "end": 19.192
    },
    {
     "w": "看",
     "start": 19.192,
     "end": 19.298
    },
    {
     "w": "原理",
     "start": 19.31,
     "end": 19.723
    },
    {
     "w": "Opus",
     "start": 20.065,
     "end": 20.655
    },
    {
     "w": "5.5 只",
     "start": 20.678,
     "end": 21.256
    },
    {
     "w": "输出",
     "start": 21.28,
     "end": 21.551
    },
    {
     "w": "文字",
     "start": 21.563,
     "end": 21.94
    },
    {
     "w": "不",
     "start": 22.129,
     "end": 22.294
    },
    {
     "w": "直接",
     "start": 22.294,
     "end": 22.553
    },
    {
     "w": "出",
     "start": 22.565,
     "end": 22.683
    },
    {
     "w": "视频",
     "start": 22.695,
     "end": 23.166
    }
   ],
   "subs": [
    {
     "text": "先看原理：Opus 5.5 只输出文字",
     "start": 18.98,
     "end": 22.129
    },
    {
     "text": "不直接出视频",
     "start": 22.129,
     "end": 23.316
    }
   ]
  },
  {
   "id": "s03_text.2",
   "scene": "s03_text",
   "text": "它写分镜、写代码、调工具，画画的是浏览器和图形引擎。",
   "start": 23.386,
   "end": 28.457,
   "words": [
    {
     "w": "它",
     "start": 23.386,
     "end": 23.54
    },
    {
     "w": "写",
     "start": 23.54,
     "end": 23.669
    },
    {
     "w": "分镜",
     "start": 23.681,
     "end": 24.094
    },
    {
     "w": "写",
     "start": 24.294,
     "end": 24.495
    },
    {
     "w": "代码",
     "start": 24.507,
     "end": 24.919
    },
    {
     "w": "调",
     "start": 25.132,
     "end": 25.356
    },
    {
     "w": "工具",
     "start": 25.356,
     "end": 25.816
    },
    {
     "w": "画画",
     "start": 26.146,
     "end": 26.594
    },
    {
     "w": "的",
     "start": 26.594,
     "end": 26.735
    },
    {
     "w": "是",
     "start": 26.759,
     "end": 26.889
    },
    {
     "w": "浏览器",
     "start": 26.901,
     "end": 27.502
    },
    {
     "w": "和",
     "start": 27.526,
     "end": 27.667
    },
    {
     "w": "图形",
     "start": 27.679,
     "end": 28.009
    },
    {
     "w": "引擎",
     "start": 28.021,
     "end": 28.457
    }
   ],
   "subs": [
    {
     "text": "它写分镜、写代码、调工具",
     "start": 23.386,
     "end": 26.146
    },
    {
     "text": "画画的是浏览器和图形引擎",
     "start": 26.146,
     "end": 28.607
    }
   ]
  },
  {
   "id": "s04_render.1",
   "scene": "s04_render",
   "text": "代码视频就像一本手翻书。给一个时间，就算出那一页。",
   "start": 29.48,
   "end": 33.888,
   "words": [
    {
     "w": "代码",
     "start": 29.48,
     "end": 29.739
    },
    {
     "w": "视频",
     "start": 29.751,
     "end": 30.247
    },
    {
     "w": "就",
     "start": 30.353,
     "end": 30.518
    },
    {
     "w": "像",
     "start": 30.518,
     "end": 30.624
    },
    {
     "w": "一本",
     "start": 30.636,
     "end": 30.848
    },
    {
     "w": "手",
     "start": 30.871,
     "end": 31.025
    },
    {
     "w": "翻书",
     "start": 31.025,
     "end": 31.438
    },
    {
     "w": "给",
     "start": 31.965,
     "end": 32.072
    },
    {
     "w": "一个",
     "start": 32.083,
     "end": 32.225
    },
    {
     "w": "时间",
     "start": 32.237,
     "end": 32.767
    },
    {
     "w": "就算",
     "start": 32.98,
     "end": 33.357
    },
    {
     "w": "出",
     "start": 33.357,
     "end": 33.487
    },
    {
     "w": "那",
     "start": 33.498,
     "end": 33.581
    },
    {
     "w": "一",
     "start": 33.581,
     "end": 33.687
    },
    {
     "w": "页",
     "start": 33.687,
     "end": 33.888
    }
   ],
   "subs": [
    {
     "text": "代码视频就像一本手翻书",
     "start": 29.48,
     "end": 31.965
    },
    {
     "text": "给一个时间，就算出那一页",
     "start": 31.965,
     "end": 34.038
    }
   ]
  },
  {
   "id": "s04_render.2",
   "scene": "s04_render",
   "text": "这一幕，也是代码算出来的。",
   "start": 34.108,
   "end": 36.112,
   "words": [
    {
     "w": "这",
     "start": 34.108,
     "end": 34.296
    },
    {
     "w": "一",
     "start": 34.296,
     "end": 34.426
    },
    {
     "w": "幕",
     "start": 34.426,
     "end": 34.721
    },
    {
     "w": "也",
     "start": 34.992,
     "end": 35.122
    },
    {
     "w": "是",
     "start": 35.122,
     "end": 35.216
    },
    {
     "w": "代码",
     "start": 35.228,
     "end": 35.475
    },
    {
     "w": "算",
     "start": 35.499,
     "end": 35.676
    },
    {
     "w": "出来",
     "start": 35.676,
     "end": 35.888
    },
    {
     "w": "的",
     "start": 35.888,
     "end": 36.112
    }
   ],
   "subs": [
    {
     "text": "这一幕，也是代码算出来的",
     "start": 34.108,
     "end": 36.262
    }
   ]
  },
  {
   "id": "s04_render.3",
   "scene": "s04_render",
   "text": "比如 30 秒，每秒 30 帧，就是 900 帧。",
   "start": 36.332,
   "end": 39.858,
   "words": [
    {
     "w": "比如",
     "start": 36.332,
     "end": 36.698
    },
    {
     "w": "30 秒",
     "start": 36.721,
     "end": 37.394
    },
    {
     "w": "每",
     "start": 37.712,
     "end": 37.924
    },
    {
     "w": "秒",
     "start": 37.924,
     "end": 38.101
    },
    {
     "w": "30",
     "start": 38.125,
     "end": 38.455
    },
    {
     "w": "帧",
     "start": 38.455,
     "end": 38.703
    },
    {
     "w": "就是",
     "start": 38.879,
     "end": 39.221
    },
    {
     "w": "900",
     "start": 39.245,
     "end": 39.587
    },
    {
     "w": "帧",
     "start": 39.587,
     "end": 39.858
    }
   ],
   "subs": [
    {
     "text": "比如 30 秒，每秒 30 帧，就是 900 帧",
     "start": 36.332,
     "end": 40.008
    }
   ]
  },
  {
   "id": "s04_render.4",
   "scene": "s04_render",
   "text": "但模型不用跑 900 次，代码只写一次。",
   "start": 40.078,
   "end": 42.885,
   "words": [
    {
     "w": "但",
     "start": 40.078,
     "end": 40.231
    },
    {
     "w": "模型",
     "start": 40.243,
     "end": 40.585
    },
    {
     "w": "不用",
     "start": 40.609,
     "end": 40.809
    },
    {
     "w": "跑",
     "start": 40.821,
     "end": 40.974
    },
    {
     "w": "900 次",
     "start": 40.986,
     "end": 41.623
    },
    {
     "w": "代码",
     "start": 41.906,
     "end": 42.189
    },
    {
     "w": "只",
     "start": 42.213,
     "end": 42.378
    },
    {
     "w": "写",
     "start": 42.378,
     "end": 42.519
    },
    {
     "w": "一次",
     "start": 42.531,
     "end": 42.885
    }
   ],
   "subs": [
    {
     "text": "但模型不用跑 900 次，代码只写一次",
     "start": 40.078,
     "end": 43.035
    }
   ]
  },
  {
   "id": "s04_render.5",
   "scene": "s04_render",
   "text": "再用 FFmpeg 把这些帧拼成视频。",
   "start": 43.105,
   "end": 46.324,
   "words": [
    {
     "w": "再",
     "start": 43.105,
     "end": 43.27
    },
    {
     "w": "用",
     "start": 43.27,
     "end": 43.576
    },
    {
     "w": "F",
     "start": 43.671,
     "end": 43.954
    },
    {
     "w": "F",
     "start": 43.966,
     "end": 44.201
    },
    {
     "w": "mpeg",
     "start": 44.213,
     "end": 44.826
    },
    {
     "w": "把",
     "start": 44.921,
     "end": 45.051
    },
    {
     "w": "这些",
     "start": 45.062,
     "end": 45.322
    },
    {
     "w": "帧",
     "start": 45.334,
     "end": 45.546
    },
    {
     "w": "拼",
     "start": 45.546,
     "end": 45.699
    },
    {
     "w": "成",
     "start": 45.699,
     "end": 45.841
    },
    {
     "w": "视频",
     "start": 45.852,
     "end": 46.324
    }
   ],
   "subs": [
    {
     "text": "再用 FFmpeg 把这些帧拼成视频",
     "start": 43.105,
     "end": 46.474
    }
   ]
  },
  {
   "id": "s05_wall.1",
   "scene": "s05_wall",
   "text": "原理不难，炫不炫，差在导演功夫。",
   "start": 47.48,
   "end": 50.688,
   "words": [
    {
     "w": "原理",
     "start": 47.48,
     "end": 47.834
    },
    {
     "w": "不",
     "start": 47.846,
     "end": 48.011
    },
    {
     "w": "难",
     "start": 48.011,
     "end": 48.341
    },
    {
     "w": "炫不",
     "start": 48.6,
     "end": 49.025
    },
    {
     "w": "炫",
     "start": 49.025,
     "end": 49.32
    },
    {
     "w": "差",
     "start": 49.626,
     "end": 49.827
    },
    {
     "w": "在",
     "start": 49.838,
     "end": 49.956
    },
    {
     "w": "导演",
     "start": 49.98,
     "end": 50.31
    },
    {
     "w": "功夫",
     "start": 50.322,
     "end": 50.688
    }
   ],
   "subs": [
    {
     "text": "原理不难，炫不炫，差在导演功夫",
     "start": 47.48,
     "end": 50.838
    }
   ]
  },
  {
   "id": "s05_wall.2",
   "scene": "s05_wall",
   "text": "截至 10 月 1 日，WaytoAGI 收录了 1,704 个视频案例。",
   "start": 50.908,
   "end": 55.365,
   "words": [
    {
     "w": "截至",
     "start": 50.908,
     "end": 51.273
    },
    {
     "w": "10 月",
     "start": 51.297,
     "end": 51.544
    },
    {
     "w": "1 日",
     "start": 51.556,
     "end": 52.04
    },
    {
     "w": "Way",
     "start": 52.334,
     "end": 52.558
    },
    {
     "w": "to",
     "start": 52.57,
     "end": 52.747
    },
    {
     "w": "AGI",
     "start": 52.759,
     "end": 53.337
    },
    {
     "w": "收录",
     "start": 53.349,
     "end": 53.702
    },
    {
     "w": "了",
     "start": 53.702,
     "end": 53.809
    },
    {
     "w": "1704 个",
     "start": 53.832,
     "end": 54.799
    },
    {
     "w": "视频",
     "start": 54.823,
     "end": 55.047
    },
    {
     "w": "案例",
     "start": 55.059,
     "end": 55.365
    }
   ],
   "subs": [
    {
     "text": "截至 10 月 1 日",
     "start": 50.908,
     "end": 52.353
    },
    {
     "text": "WaytoAGI 收录了 1,704 个视频案例",
     "start": 52.353,
     "end": 55.515
    }
   ]
  },
  {
   "id": "s05_wall.3",
   "scene": "s05_wall",
   "text": "我们挑了 8 个，每个一招。",
   "start": 55.585,
   "end": 57.448,
   "words": [
    {
     "w": "我们",
     "start": 55.585,
     "end": 55.786
    },
    {
     "w": "挑",
     "start": 55.797,
     "end": 55.962
    },
    {
     "w": "了",
     "start": 55.962,
     "end": 56.033
    },
    {
     "w": "8 个",
     "start": 56.045,
     "end": 56.434
    },
    {
     "w": "每个",
     "start": 56.741,
     "end": 57.047
    },
    {
     "w": "一",
     "start": 57.059,
     "end": 57.177
    },
    {
     "w": "招",
     "start": 57.177,
     "end": 57.448
    }
   ],
   "subs": [
    {
     "text": "我们挑了 8 个，每个一招",
     "start": 55.585,
     "end": 57.598
    }
   ]
  },
  {
   "id": "s06_c1.1",
   "scene": "s06_c1",
   "text": "第一招来自一段界面动画：一个形状贯穿全片。",
   "start": 58.48,
   "end": 61.9,
   "words": [
    {
     "w": "第一",
     "start": 58.48,
     "end": 58.692
    },
    {
     "w": "招",
     "start": 58.692,
     "end": 58.928
    },
    {
     "w": "来自",
     "start": 58.952,
     "end": 59.176
    },
    {
     "w": "一段",
     "start": 59.188,
     "end": 59.412
    },
    {
     "w": "界面",
     "start": 59.435,
     "end": 59.659
    },
    {
     "w": "动画",
     "start": 59.671,
     "end": 60.096
    },
    {
     "w": "一个",
     "start": 60.39,
     "end": 60.603
    },
    {
     "w": "形状",
     "start": 60.614,
     "end": 61.074
    },
    {
     "w": "贯穿",
     "start": 61.098,
     "end": 61.428
    },
    {
     "w": "全片",
     "start": 61.44,
     "end": 61.9
    }
   ],
   "subs": [
    {
     "text": "第一招来自一段界面动画",
     "start": 58.48,
     "end": 60.39
    },
    {
     "text": "一个形状贯穿全片",
     "start": 60.39,
     "end": 62.05
    }
   ]
  },
  {
   "id": "s06_c1.2",
   "scene": "s06_c1",
   "text": "从按钮变成图表，14 秒一刀没剪。",
   "start": 62.12,
   "end": 65.139,
   "words": [
    {
     "w": "从",
     "start": 62.12,
     "end": 62.32
    },
    {
     "w": "按钮",
     "start": 62.332,
     "end": 62.768
    },
    {
     "w": "变成",
     "start": 62.792,
     "end": 63.063
    },
    {
     "w": "图表",
     "start": 63.075,
     "end": 63.582
    },
    {
     "w": "14 秒",
     "start": 63.759,
     "end": 64.443
    },
    {
     "w": "一",
     "start": 64.467,
     "end": 64.608
    },
    {
     "w": "刀",
     "start": 64.608,
     "end": 64.75
    },
    {
     "w": "没",
     "start": 64.761,
     "end": 64.915
    },
    {
     "w": "剪",
     "start": 64.915,
     "end": 65.139
    }
   ],
   "subs": [
    {
     "text": "从按钮变成图表，14 秒一刀没剪",
     "start": 62.12,
     "end": 65.289
    }
   ]
  },
  {
   "id": "s06_c1.3",
   "scene": "s06_c1",
   "text": "想照搬，就先定贯穿对象，再让变化踩上节拍。",
   "start": 65.359,
   "end": 68.955,
   "words": [
    {
     "w": "想",
     "start": 65.359,
     "end": 65.583
    },
    {
     "w": "照搬",
     "start": 65.583,
     "end": 66.043
    },
    {
     "w": "就",
     "start": 66.231,
     "end": 66.373
    },
    {
     "w": "先",
     "start": 66.373,
     "end": 66.538
    },
    {
     "w": "定",
     "start": 66.55,
     "end": 66.703
    },
    {
     "w": "贯穿",
     "start": 66.703,
     "end": 66.998
    },
    {
     "w": "对象",
     "start": 67.01,
     "end": 67.363
    },
    {
     "w": "再",
     "start": 67.694,
     "end": 67.835
    },
    {
     "w": "让",
     "start": 67.835,
     "end": 67.941
    },
    {
     "w": "变化",
     "start": 67.953,
     "end": 68.271
    },
    {
     "w": "踩上",
     "start": 68.295,
     "end": 68.59
    },
    {
     "w": "节拍",
     "start": 68.59,
     "end": 68.955
    }
   ],
   "subs": [
    {
     "text": "想照搬，就先定贯穿对象，再让变化踩上节拍",
     "start": 65.359,
     "end": 69.105
    }
   ]
  },
  {
   "id": "s07_c2.1",
   "scene": "s07_c2",
   "text": "第二招出自一支白纸黑墨的动画：暖色只留给高潮。",
   "start": 69.98,
   "end": 73.718,
   "words": [
    {
     "w": "第二",
     "start": 69.98,
     "end": 70.204
    },
    {
     "w": "招",
     "start": 70.204,
     "end": 70.404
    },
    {
     "w": "出自",
     "start": 70.428,
     "end": 70.64
    },
    {
     "w": "一",
     "start": 70.652,
     "end": 70.758
    },
    {
     "w": "支",
     "start": 70.758,
     "end": 70.9
    },
    {
     "w": "白纸",
     "start": 70.923,
     "end": 71.206
    },
    {
     "w": "黑墨",
     "start": 71.218,
     "end": 71.466
    },
    {
     "w": "的",
     "start": 71.466,
     "end": 71.537
    },
    {
     "w": "动画",
     "start": 71.548,
     "end": 71.961
    },
    {
     "w": "暖色",
     "start": 72.291,
     "end": 72.834
    },
    {
     "w": "只",
     "start": 72.857,
     "end": 72.999
    },
    {
     "w": "留给",
     "start": 73.011,
     "end": 73.211
    },
    {
     "w": "高潮",
     "start": 73.223,
     "end": 73.718
    }
   ],
   "subs": [
    {
     "text": "第二招出自一支白纸黑墨的动画",
     "start": 69.98,
     "end": 72.291
    },
    {
     "text": "暖色只留给高潮",
     "start": 72.291,
     "end": 73.868
    }
   ]
  },
  {
   "id": "s07_c2.2",
   "scene": "s07_c2",
   "text": "全片 60 秒，暖光只亮 9 秒。",
   "start": 73.938,
   "end": 76.58,
   "words": [
    {
     "w": "全片",
     "start": 73.938,
     "end": 74.386
    },
    {
     "w": "60 秒",
     "start": 74.41,
     "end": 74.976
    },
    {
     "w": "暖",
     "start": 75.212,
     "end": 75.507
    },
    {
     "w": "光",
     "start": 75.507,
     "end": 75.766
    },
    {
     "w": "只",
     "start": 75.79,
     "end": 75.978
    },
    {
     "w": "亮",
     "start": 75.978,
     "end": 76.132
    },
    {
     "w": "9 秒",
     "start": 76.143,
     "end": 76.58
    }
   ],
   "subs": [
    {
     "text": "全片 60 秒，暖光只亮 9 秒",
     "start": 73.938,
     "end": 76.73
    }
   ]
  },
  {
   "id": "s07_c2.3",
   "scene": "s07_c2",
   "text": "这就叫把风格拆成能检查的规则。",
   "start": 76.8,
   "end": 79.382,
   "words": [
    {
     "w": "这",
     "start": 76.8,
     "end": 77.012
    },
    {
     "w": "就",
     "start": 77.012,
     "end": 77.118
    },
    {
     "w": "叫",
     "start": 77.118,
     "end": 77.212
    },
    {
     "w": "把",
     "start": 77.236,
     "end": 77.319
    },
    {
     "w": "风格",
     "start": 77.33,
     "end": 77.873
    },
    {
     "w": "拆成",
     "start": 77.979,
     "end": 78.368
    },
    {
     "w": "能",
     "start": 78.368,
     "end": 78.498
    },
    {
     "w": "检查",
     "start": 78.51,
     "end": 78.816
    },
    {
     "w": "的",
     "start": 78.816,
     "end": 78.887
    },
    {
     "w": "规则",
     "start": 78.899,
     "end": 79.382
    }
   ],
   "subs": [
    {
     "text": "这就叫把风格拆成能检查的规则",
     "start": 76.8,
     "end": 79.532
    }
   ]
  },
  {
   "id": "s08_c3.1",
   "scene": "s08_c3",
   "text": "第三招来自一支讲 AI 历史的短片。画面、旁白、配乐分层做，每层单独改。",
   "start": 80.48,
   "end": 87.128,
   "words": [
    {
     "w": "第三",
     "start": 80.48,
     "end": 80.822
    },
    {
     "w": "招",
     "start": 80.822,
     "end": 81.093
    },
    {
     "w": "来自",
     "start": 81.117,
     "end": 81.364
    },
    {
     "w": "一",
     "start": 81.376,
     "end": 81.447
    },
    {
     "w": "支",
     "start": 81.447,
     "end": 81.612
    },
    {
     "w": "讲",
     "start": 81.636,
     "end": 81.86
    },
    {
     "w": "AI",
     "start": 81.86,
     "end": 82.19
    },
    {
     "w": "历史",
     "start": 82.202,
     "end": 82.426
    },
    {
     "w": "的",
     "start": 82.426,
     "end": 82.496
    },
    {
     "w": "短片",
     "start": 82.508,
     "end": 82.933
    },
    {
     "w": "画面",
     "start": 83.472,
     "end": 83.98
    },
    {
     "w": "旁白",
     "start": 84.227,
     "end": 84.758
    },
    {
     "w": "配乐",
     "start": 85.005,
     "end": 85.277
    },
    {
     "w": "分层",
     "start": 85.3,
     "end": 85.654
    },
    {
     "w": "做",
     "start": 85.654,
     "end": 85.89
    },
    {
     "w": "每",
     "start": 86.126,
     "end": 86.362
    },
    {
     "w": "层",
     "start": 86.362,
     "end": 86.55
    },
    {
     "w": "单",
     "start": 86.574,
     "end": 86.751
    },
    {
     "w": "独改",
     "start": 86.751,
     "end": 87.128
    }
   ],
   "subs": [
    {
     "text": "第三招来自一支讲 AI 历史的短片",
     "start": 80.48,
     "end": 83.472
    },
    {
     "text": "画面、旁白、配乐分层做，每层单独改",
     "start": 83.472,
     "end": 87.278
    }
   ]
  },
  {
   "id": "s08_c3.2",
   "scene": "s08_c3",
   "text": "再把三层对齐同一条时间轴。",
   "start": 87.348,
   "end": 89.483,
   "words": [
    {
     "w": "再",
     "start": 87.348,
     "end": 87.501
    },
    {
     "w": "把",
     "start": 87.501,
     "end": 87.584
    },
    {
     "w": "三",
     "start": 87.596,
     "end": 87.82
    },
    {
     "w": "层",
     "start": 87.82,
     "end": 88.185
    },
    {
     "w": "对",
     "start": 88.292,
     "end": 88.445
    },
    {
     "w": "齐",
     "start": 88.445,
     "end": 88.551
    },
    {
     "w": "同",
     "start": 88.575,
     "end": 88.74
    },
    {
     "w": "一条",
     "start": 88.74,
     "end": 88.928
    },
    {
     "w": "时间",
     "start": 88.94,
     "end": 89.223
    },
    {
     "w": "轴",
     "start": 89.223,
     "end": 89.483
    }
   ],
   "subs": [
    {
     "text": "再把三层对齐同一条时间轴",
     "start": 87.348,
     "end": 89.633
    }
   ]
  },
  {
   "id": "s09_c4.1",
   "scene": "s09_c4",
   "text": "第四招出自一部拿破仑战役片：用真实数据当约束。",
   "start": 90.48,
   "end": 94.336,
   "words": [
    {
     "w": "第四",
     "start": 90.48,
     "end": 90.787
    },
    {
     "w": "招",
     "start": 90.787,
     "end": 91.011
    },
    {
     "w": "出自",
     "start": 91.034,
     "end": 91.27
    },
    {
     "w": "一",
     "start": 91.282,
     "end": 91.376
    },
    {
     "w": "部",
     "start": 91.376,
     "end": 91.553
    },
    {
     "w": "拿破仑",
     "start": 91.577,
     "end": 91.966
    },
    {
     "w": "战役片",
     "start": 91.978,
     "end": 92.473
    },
    {
     "w": "用",
     "start": 92.756,
     "end": 93.004
    },
    {
     "w": "真实",
     "start": 93.027,
     "end": 93.334
    },
    {
     "w": "数据",
     "start": 93.346,
     "end": 93.782
    },
    {
     "w": "当",
     "start": 93.805,
     "end": 93.959
    },
    {
     "w": "约束",
     "start": 93.971,
     "end": 94.336
    }
   ],
   "subs": [
    {
     "text": "第四招出自一部拿破仑战役片",
     "start": 90.48,
     "end": 92.756
    },
    {
     "text": "用真实数据当约束",
     "start": 92.756,
     "end": 94.486
    }
   ]
  },
  {
   "id": "s09_c4.2",
   "scene": "s09_c4",
   "text": "地形来自海拔数据，地图讲部队移动，地面镜头给情绪。",
   "start": 94.556,
   "end": 99.061,
   "words": [
    {
     "w": "地形",
     "start": 94.556,
     "end": 94.922
    },
    {
     "w": "来自",
     "start": 94.934,
     "end": 95.228
    },
    {
     "w": "海拔",
     "start": 95.252,
     "end": 95.547
    },
    {
     "w": "数据",
     "start": 95.559,
     "end": 96.077
    },
    {
     "w": "地图",
     "start": 96.467,
     "end": 96.809
    },
    {
     "w": "讲",
     "start": 96.82,
     "end": 97.021
    },
    {
     "w": "部队",
     "start": 97.044,
     "end": 97.257
    },
    {
     "w": "移动",
     "start": 97.268,
     "end": 97.646
    },
    {
     "w": "地面",
     "start": 97.858,
     "end": 98.153
    },
    {
     "w": "镜头",
     "start": 98.165,
     "end": 98.483
    },
    {
     "w": "给",
     "start": 98.507,
     "end": 98.601
    },
    {
     "w": "情绪",
     "start": 98.613,
     "end": 99.061
    }
   ],
   "subs": [
    {
     "text": "地形来自海拔数据，地图讲部队移动",
     "start": 94.556,
     "end": 97.858
    },
    {
     "text": "地面镜头给情绪",
     "start": 97.858,
     "end": 99.211
    }
   ]
  },
  {
   "id": "s09_c4.3",
   "scene": "s09_c4",
   "text": "照这样做，每个镜头都写清依据和用意。",
   "start": 99.281,
   "end": 102.465,
   "words": [
    {
     "w": "照",
     "start": 99.281,
     "end": 99.47
    },
    {
     "w": "这样",
     "start": 99.481,
     "end": 99.741
    },
    {
     "w": "做",
     "start": 99.741,
     "end": 100.059
    },
    {
     "w": "每个",
     "start": 100.307,
     "end": 100.625
    },
    {
     "w": "镜头",
     "start": 100.637,
     "end": 101.062
    },
    {
     "w": "都",
     "start": 101.085,
     "end": 101.203
    },
    {
     "w": "写清",
     "start": 101.203,
     "end": 101.51
    },
    {
     "w": "依据",
     "start": 101.533,
     "end": 101.958
    },
    {
     "w": "和",
     "start": 101.981,
     "end": 102.088
    },
    {
     "w": "用意",
     "start": 102.099,
     "end": 102.465
    }
   ],
   "subs": [
    {
     "text": "照这样做，每个镜头都写清依据和用意",
     "start": 99.281,
     "end": 102.615
    }
   ]
  },
  {
   "id": "s10_c5.1",
   "scene": "s10_c5",
   "text": "不过后四招，画面里还用了现成素材或别的 AI 模型。",
   "start": 103.48,
   "end": 108.103,
   "words": [
    {
     "w": "不过",
     "start": 103.48,
     "end": 103.775
    },
    {
     "w": "后",
     "start": 103.798,
     "end": 103.975
    },
    {
     "w": "四招",
     "start": 103.975,
     "end": 104.412
    },
    {
     "w": "画面",
     "start": 104.801,
     "end": 105.202
    },
    {
     "w": "里",
     "start": 105.202,
     "end": 105.449
    },
    {
     "w": "还",
     "start": 105.473,
     "end": 105.638
    },
    {
     "w": "用",
     "start": 105.65,
     "end": 105.756
    },
    {
     "w": "了",
     "start": 105.756,
     "end": 105.85
    },
    {
     "w": "现成",
     "start": 105.874,
     "end": 106.251
    },
    {
     "w": "素材",
     "start": 106.263,
     "end": 106.794
    },
    {
     "w": "或",
     "start": 106.888,
     "end": 107.088
    },
    {
     "w": "别的",
     "start": 107.1,
     "end": 107.348
    },
    {
     "w": "AI",
     "start": 107.371,
     "end": 107.666
    },
    {
     "w": "模型",
     "start": 107.678,
     "end": 108.103
    }
   ],
   "subs": [
    {
     "text": "不过后四招",
     "start": 103.48,
     "end": 104.801
    },
    {
     "text": "画面里还用了现成素材或别的 AI 模型",
     "start": 104.801,
     "end": 108.253
    }
   ]
  },
  {
   "id": "s10_c5.2",
   "scene": "s10_c5",
   "text": "第五招来自一支网站宣传片。用户怎么点，镜头就怎么走。",
   "start": 108.323,
   "end": 112.99,
   "words": [
    {
     "w": "第五",
     "start": 108.323,
     "end": 108.617
    },
    {
     "w": "招",
     "start": 108.617,
     "end": 108.912
    },
    {
     "w": "来自",
     "start": 109.018,
     "end": 109.278
    },
    {
     "w": "一",
     "start": 109.29,
     "end": 109.396
    },
    {
     "w": "支",
     "start": 109.396,
     "end": 109.478
    },
    {
     "w": "网站",
     "start": 109.502,
     "end": 109.785
    },
    {
     "w": "宣传片",
     "start": 109.797,
     "end": 110.339
    },
    {
     "w": "用户",
     "start": 110.879,
     "end": 111.268
    },
    {
     "w": "怎么",
     "start": 111.28,
     "end": 111.516
    },
    {
     "w": "点",
     "start": 111.516,
     "end": 111.799
    },
    {
     "w": "镜头",
     "start": 112.105,
     "end": 112.471
    },
    {
     "w": "就",
     "start": 112.494,
     "end": 112.589
    },
    {
     "w": "怎么",
     "start": 112.589,
     "end": 112.754
    },
    {
     "w": "走",
     "start": 112.754,
     "end": 112.99
    }
   ],
   "subs": [
    {
     "text": "第五招来自一支网站宣传片",
     "start": 108.323,
     "end": 110.879
    },
    {
     "text": "用户怎么点，镜头就怎么走",
     "start": 110.879,
     "end": 113.14
    }
   ]
  },
  {
   "id": "s10_c5.3",
   "scene": "s10_c5",
   "text": "换成你，每个卖点都配一段真实界面。",
   "start": 113.21,
   "end": 116.099,
   "words": [
    {
     "w": "换成",
     "start": 113.21,
     "end": 113.611
    },
    {
     "w": "你",
     "start": 113.611,
     "end": 113.941
    },
    {
     "w": "每个",
     "start": 114.306,
     "end": 114.589
    },
    {
     "w": "卖点",
     "start": 114.601,
     "end": 114.896
    },
    {
     "w": "都",
     "start": 114.92,
     "end": 114.99
    },
    {
     "w": "配",
     "start": 115.002,
     "end": 115.132
    },
    {
     "w": "一段",
     "start": 115.132,
     "end": 115.368
    },
    {
     "w": "真实",
     "start": 115.391,
     "end": 115.71
    },
    {
     "w": "界面",
     "start": 115.721,
     "end": 116.099
    }
   ],
   "subs": [
    {
     "text": "换成你，每个卖点都配一段真实界面",
     "start": 113.21,
     "end": 116.249
    }
   ]
  },
  {
   "id": "s11_c6.1",
   "scene": "s11_c6",
   "text": "接着是一支手机概念片。第六招，产品不动，只换演出。",
   "start": 116.98,
   "end": 121.954,
   "words": [
    {
     "w": "接着",
     "start": 116.98,
     "end": 117.452
    },
    {
     "w": "是",
     "start": 117.475,
     "end": 117.605
    },
    {
     "w": "一",
     "start": 117.617,
     "end": 117.711
    },
    {
     "w": "支",
     "start": 117.711,
     "end": 117.805
    },
    {
     "w": "手机",
     "start": 117.829,
     "end": 118.124
    },
    {
     "w": "概念片",
     "start": 118.136,
     "end": 118.666
    },
    {
     "w": "第六",
     "start": 119.206,
     "end": 119.524
    },
    {
     "w": "招",
     "start": 119.524,
     "end": 119.819
    },
    {
     "w": "产品",
     "start": 120.114,
     "end": 120.503
    },
    {
     "w": "不",
     "start": 120.515,
     "end": 120.645
    },
    {
     "w": "动",
     "start": 120.645,
     "end": 120.845
    },
    {
     "w": "只",
     "start": 121.14,
     "end": 121.352
    },
    {
     "w": "换",
     "start": 121.352,
     "end": 121.541
    },
    {
     "w": "演出",
     "start": 121.553,
     "end": 121.954
    }
   ],
   "subs": [
    {
     "text": "接着是一支手机概念片",
     "start": 116.98,
     "end": 119.206
    },
    {
     "text": "第六招，产品不动，只换演出",
     "start": 119.206,
     "end": 122.104
    }
   ]
  },
  {
   "id": "s11_c6.2",
   "scene": "s11_c6",
   "text": "同一个 3D 模型，换了几种风格。",
   "start": 122.174,
   "end": 124.638,
   "words": [
    {
     "w": "同",
     "start": 122.174,
     "end": 122.362
    },
    {
     "w": "一个",
     "start": 122.362,
     "end": 122.516
    },
    {
     "w": "3",
     "start": 122.539,
     "end": 122.763
    },
    {
     "w": "D",
     "start": 122.763,
     "end": 122.869
    },
    {
     "w": "模型",
     "start": 122.881,
     "end": 123.376
    },
    {
     "w": "换",
     "start": 123.6,
     "end": 123.801
    },
    {
     "w": "了",
     "start": 123.801,
     "end": 123.872
    },
    {
     "w": "几",
     "start": 123.884,
     "end": 124.049
    },
    {
     "w": "种",
     "start": 124.049,
     "end": 124.178
    },
    {
     "w": "风格",
     "start": 124.19,
     "end": 124.638
    }
   ],
   "subs": [
    {
     "text": "同一个 3D 模型，换了几种风格",
     "start": 122.174,
     "end": 124.788
    }
   ]
  },
  {
   "id": "s11_c6.3",
   "scene": "s11_c6",
   "text": "你也可以把模型锁死，只改镜头、光线和配色。",
   "start": 124.858,
   "end": 128.42,
   "words": [
    {
     "w": "你",
     "start": 124.858,
     "end": 125.0
    },
    {
     "w": "也",
     "start": 125.0,
     "end": 125.082
    },
    {
     "w": "可以",
     "start": 125.094,
     "end": 125.271
    },
    {
     "w": "把",
     "start": 125.271,
     "end": 125.377
    },
    {
     "w": "模型",
     "start": 125.389,
     "end": 125.695
    },
    {
     "w": "锁",
     "start": 125.707,
     "end": 125.872
    },
    {
     "w": "死",
     "start": 125.872,
     "end": 126.167
    },
    {
     "w": "只",
     "start": 126.415,
     "end": 126.627
    },
    {
     "w": "改",
     "start": 126.627,
     "end": 126.78
    },
    {
     "w": "镜头",
     "start": 126.792,
     "end": 127.299
    },
    {
     "w": "光线",
     "start": 127.547,
     "end": 127.936
    },
    {
     "w": "和",
     "start": 127.96,
     "end": 128.019
    },
    {
     "w": "配色",
     "start": 128.03,
     "end": 128.42
    }
   ],
   "subs": [
    {
     "text": "你也可以把模型锁死，只改镜头、光线和配色",
     "start": 124.858,
     "end": 128.57
    }
   ]
  },
  {
   "id": "s12_c7.1",
   "scene": "s12_c7",
   "text": "第七招藏在一支舞蹈 MV 里：让动作驱动特效。",
   "start": 129.48,
   "end": 133.006,
   "words": [
    {
     "w": "第七",
     "start": 129.48,
     "end": 129.787
    },
    {
     "w": "招",
     "start": 129.787,
     "end": 130.022
    },
    {
     "w": "藏",
     "start": 130.046,
     "end": 130.235
    },
    {
     "w": "在",
     "start": 130.235,
     "end": 130.317
    },
    {
     "w": "一",
     "start": 130.329,
     "end": 130.435
    },
    {
     "w": "支",
     "start": 130.435,
     "end": 130.553
    },
    {
     "w": "舞蹈",
     "start": 130.577,
     "end": 130.86
    },
    {
     "w": "MV",
     "start": 130.871,
     "end": 131.214
    },
    {
     "w": "里",
     "start": 131.214,
     "end": 131.402
    },
    {
     "w": "让",
     "start": 131.626,
     "end": 131.839
    },
    {
     "w": "动作",
     "start": 131.85,
     "end": 132.251
    },
    {
     "w": "驱动",
     "start": 132.275,
     "end": 132.593
    },
    {
     "w": "特效",
     "start": 132.605,
     "end": 133.006
    }
   ],
   "subs": [
    {
     "text": "第七招藏在一支舞蹈 MV 里",
     "start": 129.48,
     "end": 131.626
    },
    {
     "text": "让动作驱动特效",
     "start": 131.626,
     "end": 133.156
    }
   ]
  },
  {
   "id": "s12_c7.2",
   "scene": "s12_c7",
   "text": "据作者说，舞者和歌曲是 AI 生成的，人体骨架数据让歌词跟着手走。",
   "start": 133.226,
   "end": 139.252,
   "words": [
    {
     "w": "据",
     "start": 133.226,
     "end": 133.415
    },
    {
     "w": "作者",
     "start": 133.426,
     "end": 133.639
    },
    {
     "w": "说",
     "start": 133.639,
     "end": 133.945
    },
    {
     "w": "舞者",
     "start": 134.323,
     "end": 134.688
    },
    {
     "w": "和",
     "start": 134.712,
     "end": 134.83
    },
    {
     "w": "歌曲",
     "start": 134.842,
     "end": 135.349
    },
    {
     "w": "是",
     "start": 135.443,
     "end": 135.632
    },
    {
     "w": "AI",
     "start": 135.643,
     "end": 135.974
    },
    {
     "w": "生成",
     "start": 135.985,
     "end": 136.339
    },
    {
     "w": "的",
     "start": 136.339,
     "end": 136.504
    },
    {
     "w": "人体",
     "start": 136.799,
     "end": 137.176
    },
    {
     "w": "骨架",
     "start": 137.188,
     "end": 137.448
    },
    {
     "w": "数据",
     "start": 137.459,
     "end": 137.955
    },
    {
     "w": "让",
     "start": 138.049,
     "end": 138.238
    },
    {
     "w": "歌词",
     "start": 138.25,
     "end": 138.674
    },
    {
     "w": "跟着",
     "start": 138.698,
     "end": 138.875
    },
    {
     "w": "手走",
     "start": 138.886,
     "end": 139.252
    }
   ],
   "subs": [
    {
     "text": "据作者说，舞者和歌曲是 AI 生成的",
     "start": 133.226,
     "end": 136.799
    },
    {
     "text": "人体骨架数据让歌词跟着手走",
     "start": 136.799,
     "end": 139.402
    }
   ]
  },
  {
   "id": "s12_c7.3",
   "scene": "s12_c7",
   "text": "别贪多，挑两三个动作，各绑一种效果。",
   "start": 139.472,
   "end": 142.337,
   "words": [
    {
     "w": "别",
     "start": 139.472,
     "end": 139.637
    },
    {
     "w": "贪多",
     "start": 139.637,
     "end": 140.038
    },
    {
     "w": "挑",
     "start": 140.262,
     "end": 140.439
    },
    {
     "w": "两",
     "start": 140.451,
     "end": 140.604
    },
    {
     "w": "三",
     "start": 140.604,
     "end": 140.757
    },
    {
     "w": "个",
     "start": 140.757,
     "end": 140.816
    },
    {
     "w": "动作",
     "start": 140.828,
     "end": 141.194
    },
    {
     "w": "各",
     "start": 141.559,
     "end": 141.701
    },
    {
     "w": "绑",
     "start": 141.701,
     "end": 141.783
    },
    {
     "w": "一种",
     "start": 141.795,
     "end": 141.96
    },
    {
     "w": "效果",
     "start": 141.972,
     "end": 142.337
    }
   ],
   "subs": [
    {
     "text": "别贪多，挑两三个动作，各绑一种效果",
     "start": 139.472,
     "end": 142.487
    }
   ]
  },
  {
   "id": "s13_c8.1",
   "scene": "s13_c8",
   "text": "最后一招来自一部舞台短片：多个模型各管一段。",
   "start": 143.48,
   "end": 147.065,
   "words": [
    {
     "w": "最后",
     "start": 143.48,
     "end": 143.763
    },
    {
     "w": "一",
     "start": 143.775,
     "end": 143.869
    },
    {
     "w": "招",
     "start": 143.869,
     "end": 144.164
    },
    {
     "w": "来自",
     "start": 144.27,
     "end": 144.541
    },
    {
     "w": "一",
     "start": 144.553,
     "end": 144.624
    },
    {
     "w": "部",
     "start": 144.624,
     "end": 144.718
    },
    {
     "w": "舞台",
     "start": 144.742,
     "end": 144.989
    },
    {
     "w": "短片",
     "start": 145.001,
     "end": 145.438
    },
    {
     "w": "多个",
     "start": 145.803,
     "end": 146.039
    },
    {
     "w": "模型",
     "start": 146.051,
     "end": 146.428
    },
    {
     "w": "各",
     "start": 146.452,
     "end": 146.617
    },
    {
     "w": "管",
     "start": 146.617,
     "end": 146.758
    },
    {
     "w": "一段",
     "start": 146.77,
     "end": 147.065
    }
   ],
   "subs": [
    {
     "text": "最后一招来自一部舞台短片",
     "start": 143.48,
     "end": 145.803
    },
    {
     "text": "多个模型各管一段",
     "start": 145.803,
     "end": 147.215
    }
   ]
  },
  {
   "id": "s13_c8.2",
   "scene": "s13_c8",
   "text": "据作者说，Opus 写代码统筹，人物和布景交给别的模型。",
   "start": 147.285,
   "end": 152.049,
   "words": [
    {
     "w": "据",
     "start": 147.285,
     "end": 147.45
    },
    {
     "w": "作者",
     "start": 147.462,
     "end": 147.674
    },
    {
     "w": "说",
     "start": 147.674,
     "end": 147.992
    },
    {
     "w": "Opus",
     "start": 148.287,
     "end": 148.783
    },
    {
     "w": "写",
     "start": 148.806,
     "end": 149.03
    },
    {
     "w": "代码",
     "start": 149.03,
     "end": 149.242
    },
    {
     "w": "统筹",
     "start": 149.254,
     "end": 149.75
    },
    {
     "w": "人物",
     "start": 150.056,
     "end": 150.434
    },
    {
     "w": "和",
     "start": 150.457,
     "end": 150.551
    },
    {
     "w": "布景",
     "start": 150.563,
     "end": 150.964
    },
    {
     "w": "交给",
     "start": 151.058,
     "end": 151.365
    },
    {
     "w": "别的",
     "start": 151.389,
     "end": 151.601
    },
    {
     "w": "模型",
     "start": 151.613,
     "end": 152.049
    }
   ],
   "subs": [
    {
     "text": "据作者说，Opus 写代码统筹",
     "start": 147.285,
     "end": 150.056
    },
    {
     "text": "人物和布景交给别的模型",
     "start": 150.056,
     "end": 152.199
    }
   ]
  },
  {
   "id": "s13_c8.3",
   "scene": "s13_c8",
   "text": "分工时，每个镜头写清谁来做、怎样算合格。",
   "start": 152.269,
   "end": 156.078,
   "words": [
    {
     "w": "分工",
     "start": 152.269,
     "end": 152.635
    },
    {
     "w": "时",
     "start": 152.635,
     "end": 153.0
    },
    {
     "w": "每个",
     "start": 153.248,
     "end": 153.578
    },
    {
     "w": "镜头",
     "start": 153.59,
     "end": 153.92
    },
    {
     "w": "写清",
     "start": 153.932,
     "end": 154.262
    },
    {
     "w": "谁",
     "start": 154.262,
     "end": 154.427
    },
    {
     "w": "来",
     "start": 154.439,
     "end": 154.58
    },
    {
     "w": "做",
     "start": 154.58,
     "end": 154.852
    },
    {
     "w": "怎样",
     "start": 155.158,
     "end": 155.5
    },
    {
     "w": "算",
     "start": 155.512,
     "end": 155.665
    },
    {
     "w": "合格",
     "start": 155.665,
     "end": 156.078
    }
   ],
   "subs": [
    {
     "text": "分工时，每个镜头写清谁来做、怎样算合格",
     "start": 152.269,
     "end": 156.228
    }
   ]
  },
  {
   "id": "s14_formula.1",
   "scene": "s14_formula",
   "text": "八招看下来，好看不是因为 Opus 会画画。",
   "start": 157.06,
   "end": 160.421,
   "words": [
    {
     "w": "八",
     "start": 157.06,
     "end": 157.249
    },
    {
     "w": "招",
     "start": 157.249,
     "end": 157.367
    },
    {
     "w": "看",
     "start": 157.378,
     "end": 157.544
    },
    {
     "w": "下来",
     "start": 157.544,
     "end": 157.909
    },
    {
     "w": "好看",
     "start": 158.204,
     "end": 158.64
    },
    {
     "w": "不是",
     "start": 158.664,
     "end": 158.876
    },
    {
     "w": "因为",
     "start": 158.888,
     "end": 159.194
    },
    {
     "w": "Opus",
     "start": 159.301,
     "end": 159.843
    },
    {
     "w": "会",
     "start": 159.867,
     "end": 160.02
    },
    {
     "w": "画画",
     "start": 160.032,
     "end": 160.421
    }
   ],
   "subs": [
    {
     "text": "八招看下来，好看不是因为 Opus 会画画",
     "start": 157.06,
     "end": 160.571
    }
   ]
  },
  {
   "id": "s14_formula.2",
   "scene": "s14_formula",
   "text": "而是叙事、规则、时间轴、声音，加上反复检查。",
   "start": 160.641,
   "end": 165.606,
   "words": [
    {
     "w": "而是",
     "start": 160.641,
     "end": 160.936
    },
    {
     "w": "叙事",
     "start": 160.959,
     "end": 161.549
    },
    {
     "w": "规则",
     "start": 161.761,
     "end": 162.374
    },
    {
     "w": "时间",
     "start": 162.634,
     "end": 163.047
    },
    {
     "w": "轴",
     "start": 163.047,
     "end": 163.353
    },
    {
     "w": "声音",
     "start": 163.518,
     "end": 164.084
    },
    {
     "w": "加上",
     "start": 164.285,
     "end": 164.698
    },
    {
     "w": "反复",
     "start": 164.721,
     "end": 165.098
    },
    {
     "w": "检查",
     "start": 165.11,
     "end": 165.606
    }
   ],
   "subs": [
    {
     "text": "而是叙事、规则、时间轴、声音，加上反复检查",
     "start": 160.641,
     "end": 165.756
    }
   ]
  },
  {
   "id": "s14_formula.3",
   "scene": "s14_formula",
   "text": "这是导演功夫：方向和反馈靠你，代码交给它。",
   "start": 165.826,
   "end": 169.481,
   "words": [
    {
     "w": "这",
     "start": 165.826,
     "end": 165.967
    },
    {
     "w": "是",
     "start": 165.967,
     "end": 166.073
    },
    {
     "w": "导演",
     "start": 166.085,
     "end": 166.368
    },
    {
     "w": "功夫",
     "start": 166.38,
     "end": 166.781
    },
    {
     "w": "方向",
     "start": 167.123,
     "end": 167.559
    },
    {
     "w": "和",
     "start": 167.583,
     "end": 167.653
    },
    {
     "w": "反馈",
     "start": 167.665,
     "end": 167.984
    },
    {
     "w": "靠",
     "start": 167.995,
     "end": 168.184
    },
    {
     "w": "你",
     "start": 168.184,
     "end": 168.42
    },
    {
     "w": "代码",
     "start": 168.738,
     "end": 168.974
    },
    {
     "w": "交给",
     "start": 168.998,
     "end": 169.245
    },
    {
     "w": "它",
     "start": 169.245,
     "end": 169.481
    }
   ],
   "subs": [
    {
     "text": "这是导演功夫：方向和反馈靠你，代码交给它",
     "start": 165.826,
     "end": 169.631
    }
   ]
  },
  {
   "id": "s15_env.1",
   "scene": "s15_env",
   "text": "轮到你了，一共六步。第一步，准备一个能运行代码的 AI 工具，比如 Claude Code。",
   "start": 170.48,
   "end": 176.975,
   "words": [
    {
     "w": "轮",
     "start": 170.48,
     "end": 170.657
    },
    {
     "w": "到",
     "start": 170.657,
     "end": 170.787
    },
    {
     "w": "你",
     "start": 170.798,
     "end": 170.928
    },
    {
     "w": "了",
     "start": 170.928,
     "end": 171.152
    },
    {
     "w": "一共",
     "start": 171.459,
     "end": 171.706
    },
    {
     "w": "六步",
     "start": 171.718,
     "end": 172.072
    },
    {
     "w": "第一",
     "start": 172.612,
     "end": 172.847
    },
    {
     "w": "步",
     "start": 172.847,
     "end": 173.06
    },
    {
     "w": "准备",
     "start": 173.366,
     "end": 173.614
    },
    {
     "w": "一个",
     "start": 173.626,
     "end": 173.862
    },
    {
     "w": "能",
     "start": 173.885,
     "end": 174.003
    },
    {
     "w": "运行",
     "start": 174.015,
     "end": 174.286
    },
    {
     "w": "代码",
     "start": 174.298,
     "end": 174.546
    },
    {
     "w": "的",
     "start": 174.546,
     "end": 174.675
    },
    {
     "w": "AI",
     "start": 174.699,
     "end": 175.041
    },
    {
     "w": "工具",
     "start": 175.053,
     "end": 175.454
    },
    {
     "w": "比如",
     "start": 175.713,
     "end": 176.126
    },
    {
     "w": "Claude",
     "start": 176.22,
     "end": 176.586
    },
    {
     "w": "Code",
     "start": 176.597,
     "end": 176.975
    }
   ],
   "subs": [
    {
     "text": "轮到你了，一共六步",
     "start": 170.48,
     "end": 172.612
    },
    {
     "text": "第一步，准备一个能运行代码的 AI 工具",
     "start": 172.612,
     "end": 175.713
    },
    {
     "text": "比如 Claude Code",
     "start": 175.713,
     "end": 177.125
    }
   ]
  },
  {
   "id": "s15_env.2",
   "scene": "s15_env",
   "text": "再装 Node 和 FFmpeg。注意，Claude Code 要付费账号。",
   "start": 177.195,
   "end": 182.569,
   "words": [
    {
     "w": "再装",
     "start": 177.195,
     "end": 177.608
    },
    {
     "w": "Node",
     "start": 177.608,
     "end": 177.926
    },
    {
     "w": "和",
     "start": 178.032,
     "end": 178.256
    },
    {
     "w": "F",
     "start": 178.268,
     "end": 178.551
    },
    {
     "w": "F",
     "start": 178.563,
     "end": 178.799
    },
    {
     "w": "mpeg",
     "start": 178.81,
     "end": 179.4
    },
    {
     "w": "注意",
     "start": 179.94,
     "end": 180.388
    },
    {
     "w": "Claude",
     "start": 180.753,
     "end": 181.143
    },
    {
     "w": "Code",
     "start": 181.154,
     "end": 181.579
    },
    {
     "w": "要",
     "start": 181.685,
     "end": 181.85
    },
    {
     "w": "付费",
     "start": 181.862,
     "end": 182.157
    },
    {
     "w": "账号",
     "start": 182.168,
     "end": 182.569
    }
   ],
   "subs": [
    {
     "text": "再装 Node 和 FFmpeg",
     "start": 177.195,
     "end": 179.599
    },
    {
     "text": "注意，Claude Code 要付费账号",
     "start": 179.599,
     "end": 182.719
    }
   ]
  },
  {
   "id": "s16_routes.1",
   "scene": "s16_routes",
   "text": "第二步，选路线：HyperFrames 或 Remotion，适合做字幕、图表和界面。",
   "start": 183.48,
   "end": 188.999,
   "words": [
    {
     "w": "第二",
     "start": 183.48,
     "end": 183.728
    },
    {
     "w": "步",
     "start": 183.728,
     "end": 183.975
    },
    {
     "w": "选路线",
     "start": 184.14,
     "end": 184.742
    },
    {
     "w": "HyperFrames",
     "start": 185.025,
     "end": 185.909
    },
    {
     "w": "或",
     "start": 186.004,
     "end": 186.228
    },
    {
     "w": "Remotion",
     "start": 186.239,
     "end": 186.794
    },
    {
     "w": "适合",
     "start": 186.994,
     "end": 187.407
    },
    {
     "w": "做",
     "start": 187.419,
     "end": 187.56
    },
    {
     "w": "字幕",
     "start": 187.56,
     "end": 187.926
    },
    {
     "w": "图表",
     "start": 188.103,
     "end": 188.504
    },
    {
     "w": "和",
     "start": 188.527,
     "end": 188.645
    },
    {
     "w": "界面",
     "start": 188.657,
     "end": 188.999
    }
   ],
   "subs": [
    {
     "text": "第二步，选路线",
     "start": 183.48,
     "end": 185.025
    },
    {
     "text": "HyperFrames 或 Remotion",
     "start": 185.025,
     "end": 186.994
    },
    {
     "text": "适合做字幕、图表和界面",
     "start": 186.994,
     "end": 189.149
    }
   ]
  },
  {
   "id": "s16_routes.2",
   "scene": "s16_routes",
   "text": "想全部自己掌控，就像本片：把画面写成网页，再用一个自动截图的浏览器。",
   "start": 189.219,
   "end": 195.044,
   "words": [
    {
     "w": "想",
     "start": 189.219,
     "end": 189.466
    },
    {
     "w": "全部",
     "start": 189.49,
     "end": 189.809
    },
    {
     "w": "自己",
     "start": 189.82,
     "end": 190.044
    },
    {
     "w": "掌控",
     "start": 190.056,
     "end": 190.492
    },
    {
     "w": "就",
     "start": 190.716,
     "end": 190.846
    },
    {
     "w": "像",
     "start": 190.846,
     "end": 190.976
    },
    {
     "w": "本片",
     "start": 190.988,
     "end": 191.448
    },
    {
     "w": "把",
     "start": 191.778,
     "end": 191.908
    },
    {
     "w": "画面",
     "start": 191.919,
     "end": 192.273
    },
    {
     "w": "写成",
     "start": 192.297,
     "end": 192.603
    },
    {
     "w": "网页",
     "start": 192.603,
     "end": 193.028
    },
    {
     "w": "再",
     "start": 193.287,
     "end": 193.452
    },
    {
     "w": "用",
     "start": 193.452,
     "end": 193.547
    },
    {
     "w": "一个",
     "start": 193.559,
     "end": 193.771
    },
    {
     "w": "自动",
     "start": 193.794,
     "end": 194.125
    },
    {
     "w": "截图",
     "start": 194.136,
     "end": 194.431
    },
    {
     "w": "的",
     "start": 194.431,
     "end": 194.514
    },
    {
     "w": "浏览器",
     "start": 194.526,
     "end": 195.044
    }
   ],
   "subs": [
    {
     "text": "想全部自己掌控，就像本片：把画面写成网页",
     "start": 189.219,
     "end": 193.287
    },
    {
     "text": "再用一个自动截图的浏览器",
     "start": 193.287,
     "end": 195.194
    }
   ]
  },
  {
   "id": "s16_routes.3",
   "scene": "s16_routes",
   "text": "想要现成风格，就装 Lemo-Opuscar，再叮嘱它一句：先给我看分镜。",
   "start": 195.264,
   "end": 200.312,
   "words": [
    {
     "w": "想要",
     "start": 195.264,
     "end": 195.618
    },
    {
     "w": "现成",
     "start": 195.642,
     "end": 195.948
    },
    {
     "w": "风格",
     "start": 195.96,
     "end": 196.42
    },
    {
     "w": "就",
     "start": 196.538,
     "end": 196.738
    },
    {
     "w": "装",
     "start": 196.738,
     "end": 196.915
    },
    {
     "w": "Lemo",
     "start": 196.939,
     "end": 197.234
    },
    {
     "w": "Opuscar",
     "start": 197.246,
     "end": 197.965
    },
    {
     "w": "再",
     "start": 198.271,
     "end": 198.46
    },
    {
     "w": "叮嘱",
     "start": 198.46,
     "end": 198.696
    },
    {
     "w": "它",
     "start": 198.708,
     "end": 198.838
    },
    {
     "w": "一",
     "start": 198.849,
     "end": 198.955
    },
    {
     "w": "句",
     "start": 198.955,
     "end": 199.179
    },
    {
     "w": "先",
     "start": 199.38,
     "end": 199.639
    },
    {
     "w": "给",
     "start": 199.639,
     "end": 199.71
    },
    {
     "w": "我",
     "start": 199.722,
     "end": 199.793
    },
    {
     "w": "看",
     "start": 199.793,
     "end": 199.958
    },
    {
     "w": "分镜",
     "start": 199.97,
     "end": 200.312
    }
   ],
   "subs": [
    {
     "text": "想要现成风格",
     "start": 195.264,
     "end": 196.219
    },
    {
     "text": "就装 Lemo-Opuscar",
     "start": 196.219,
     "end": 198.402
    },
    {
     "text": "再叮嘱它一句：先给我看分镜",
     "start": 198.402,
     "end": 200.462
    }
   ]
  },
  {
   "id": "s17_prompt.1",
   "scene": "s17_prompt",
   "text": "第三步，套模板写需求。给谁看，看完记住什么，多长，哪些不能改。",
   "start": 201.48,
   "end": 208.163,
   "words": [
    {
     "w": "第三",
     "start": 201.48,
     "end": 201.857
    },
    {
     "w": "步",
     "start": 201.857,
     "end": 202.07
    },
    {
     "w": "套",
     "start": 202.305,
     "end": 202.53
    },
    {
     "w": "模板",
     "start": 202.53,
     "end": 202.907
    },
    {
     "w": "写",
     "start": 202.93,
     "end": 203.096
    },
    {
     "w": "需求",
     "start": 203.107,
     "end": 203.603
    },
    {
     "w": "给",
     "start": 204.142,
     "end": 204.296
    },
    {
     "w": "谁",
     "start": 204.296,
     "end": 204.461
    },
    {
     "w": "看",
     "start": 204.461,
     "end": 204.791
    },
    {
     "w": "看",
     "start": 205.156,
     "end": 205.345
    },
    {
     "w": "完",
     "start": 205.345,
     "end": 205.475
    },
    {
     "w": "记住",
     "start": 205.498,
     "end": 205.734
    },
    {
     "w": "什么",
     "start": 205.746,
     "end": 206.112
    },
    {
     "w": "多",
     "start": 206.442,
     "end": 206.607
    },
    {
     "w": "长",
     "start": 206.607,
     "end": 206.984
    },
    {
     "w": "哪些",
     "start": 207.338,
     "end": 207.645
    },
    {
     "w": "不能",
     "start": 207.656,
     "end": 207.892
    },
    {
     "w": "改",
     "start": 207.892,
     "end": 208.163
    }
   ],
   "subs": [
    {
     "text": "第三步，套模板写需求",
     "start": 201.48,
     "end": 204.142
    },
    {
     "text": "给谁看，看完记住什么，多长，哪些不能改",
     "start": 204.142,
     "end": 208.313
    }
   ]
  },
  {
   "id": "s17_prompt.2",
   "scene": "s17_prompt",
   "text": "风格别写高级感，写能检查的规则：每个画面一个主信息。",
   "start": 208.383,
   "end": 212.688,
   "words": [
    {
     "w": "风格",
     "start": 208.383,
     "end": 208.832
    },
    {
     "w": "别",
     "start": 208.855,
     "end": 209.008
    },
    {
     "w": "写",
     "start": 209.008,
     "end": 209.15
    },
    {
     "w": "高级",
     "start": 209.174,
     "end": 209.445
    },
    {
     "w": "感",
     "start": 209.445,
     "end": 209.669
    },
    {
     "w": "写",
     "start": 209.964,
     "end": 210.152
    },
    {
     "w": "能",
     "start": 210.152,
     "end": 210.282
    },
    {
     "w": "检查",
     "start": 210.294,
     "end": 210.565
    },
    {
     "w": "的",
     "start": 210.565,
     "end": 210.648
    },
    {
     "w": "规则",
     "start": 210.659,
     "end": 211.143
    },
    {
     "w": "每个",
     "start": 211.426,
     "end": 211.744
    },
    {
     "w": "画面",
     "start": 211.756,
     "end": 212.004
    },
    {
     "w": "一个",
     "start": 212.027,
     "end": 212.145
    },
    {
     "w": "主信息",
     "start": 212.157,
     "end": 212.688
    }
   ],
   "subs": [
    {
     "text": "风格别写高级感，写能检查的规则",
     "start": 208.383,
     "end": 211.426
    },
    {
     "text": "每个画面一个主信息",
     "start": 211.426,
     "end": 212.838
    }
   ]
  },
  {
   "id": "s18_sample.1",
   "scene": "s18_sample",
   "text": "第四步，先要分镜、三张效果图和一个小样，确认了再做全片。",
   "start": 213.98,
   "end": 219.133,
   "words": [
    {
     "w": "第四",
     "start": 213.98,
     "end": 214.298
    },
    {
     "w": "步",
     "start": 214.298,
     "end": 214.558
    },
    {
     "w": "先",
     "start": 214.817,
     "end": 215.006
    },
    {
     "w": "要",
     "start": 215.006,
     "end": 215.124
    },
    {
     "w": "分镜",
     "start": 215.136,
     "end": 215.596
    },
    {
     "w": "三",
     "start": 215.82,
     "end": 216.114
    },
    {
     "w": "张",
     "start": 216.114,
     "end": 216.244
    },
    {
     "w": "效果",
     "start": 216.256,
     "end": 216.551
    },
    {
     "w": "图",
     "start": 216.551,
     "end": 216.893
    },
    {
     "w": "和",
     "start": 216.999,
     "end": 217.152
    },
    {
     "w": "一个",
     "start": 217.164,
     "end": 217.305
    },
    {
     "w": "小样",
     "start": 217.317,
     "end": 217.754
    },
    {
     "w": "确认",
     "start": 217.989,
     "end": 218.331
    },
    {
     "w": "了",
     "start": 218.331,
     "end": 218.414
    },
    {
     "w": "再",
     "start": 218.438,
     "end": 218.567
    },
    {
     "w": "做",
     "start": 218.567,
     "end": 218.662
    },
    {
     "w": "全片",
     "start": 218.673,
     "end": 219.133
    }
   ],
   "subs": [
    {
     "text": "第四步，先要分镜、三张效果图和一个小样",
     "start": 213.98,
     "end": 217.989
    },
    {
     "text": "确认了再做全片",
     "start": 217.989,
     "end": 219.283
    }
   ]
  },
  {
   "id": "s19_feedback.1",
   "scene": "s19_feedback",
   "text": "第五步，反馈写成：时间点，问题，期望。",
   "start": 220.98,
   "end": 225.178,
   "words": [
    {
     "w": "第五",
     "start": 220.98,
     "end": 221.275
    },
    {
     "w": "步",
     "start": 221.275,
     "end": 221.546
    },
    {
     "w": "反馈",
     "start": 221.782,
     "end": 222.136
    },
    {
     "w": "写",
     "start": 222.147,
     "end": 222.289
    },
    {
     "w": "成",
     "start": 222.289,
     "end": 222.643
    },
    {
     "w": "时间点",
     "start": 222.926,
     "end": 223.598
    },
    {
     "w": "问题",
     "start": 223.905,
     "end": 224.423
    },
    {
     "w": "期望",
     "start": 224.718,
     "end": 225.178
    }
   ],
   "subs": [
    {
     "text": "第五步，反馈写成：时间点，问题，期望",
     "start": 220.98,
     "end": 225.328
    }
   ]
  },
  {
   "id": "s19_feedback.2",
   "scene": "s19_feedback",
   "text": "别说再炫一点。要说：第 8 到 11 秒，标题没读完就消失，请延长停留。",
   "start": 225.398,
   "end": 231.881,
   "words": [
    {
     "w": "别说",
     "start": 225.398,
     "end": 225.764
    },
    {
     "w": "再",
     "start": 225.787,
     "end": 225.952
    },
    {
     "w": "炫",
     "start": 225.952,
     "end": 226.117
    },
    {
     "w": "一",
     "start": 226.129,
     "end": 226.2
    },
    {
     "w": "点",
     "start": 226.2,
     "end": 226.459
    },
    {
     "w": "要",
     "start": 226.987,
     "end": 227.164
    },
    {
     "w": "说",
     "start": 227.164,
     "end": 227.506
    },
    {
     "w": "第",
     "start": 227.86,
     "end": 228.049
    },
    {
     "w": "8 到 11 秒",
     "start": 228.049,
     "end": 228.992
    },
    {
     "w": "标题",
     "start": 229.334,
     "end": 229.688
    },
    {
     "w": "没",
     "start": 229.7,
     "end": 229.841
    },
    {
     "w": "读完",
     "start": 229.841,
     "end": 230.1
    },
    {
     "w": "就",
     "start": 230.124,
     "end": 230.195
    },
    {
     "w": "消失",
     "start": 230.207,
     "end": 230.726
    },
    {
     "w": "请",
     "start": 230.891,
     "end": 231.103
    },
    {
     "w": "延长",
     "start": 231.126,
     "end": 231.445
    },
    {
     "w": "停留",
     "start": 231.457,
     "end": 231.881
    }
   ],
   "subs": [
    {
     "text": "别说再炫一点",
     "start": 225.398,
     "end": 226.987
    },
    {
     "text": "要说：第 8 到 11 秒，标题没读完就消失",
     "start": 226.987,
     "end": 230.891
    },
    {
     "text": "请延长停留",
     "start": 230.891,
     "end": 232.031
    }
   ]
  },
  {
   "id": "s20_ship.1",
   "scene": "s20_ship",
   "text": "第六步，检查：先看截图、片段，再带声音完整看一遍。",
   "start": 232.98,
   "end": 238.074,
   "words": [
    {
     "w": "第六",
     "start": 232.98,
     "end": 233.287
    },
    {
     "w": "步",
     "start": 233.287,
     "end": 233.522
    },
    {
     "w": "检查",
     "start": 233.794,
     "end": 234.36
    },
    {
     "w": "先",
     "start": 234.619,
     "end": 234.855
    },
    {
     "w": "看",
     "start": 234.855,
     "end": 234.996
    },
    {
     "w": "截图",
     "start": 235.008,
     "end": 235.527
    },
    {
     "w": "片段",
     "start": 235.739,
     "end": 236.235
    },
    {
     "w": "再",
     "start": 236.577,
     "end": 236.742
    },
    {
     "w": "带",
     "start": 236.742,
     "end": 236.836
    },
    {
     "w": "声音",
     "start": 236.848,
     "end": 237.237
    },
    {
     "w": "完整",
     "start": 237.261,
     "end": 237.567
    },
    {
     "w": "看",
     "start": 237.579,
     "end": 237.815
    },
    {
     "w": "一",
     "start": 237.815,
     "end": 237.886
    },
    {
     "w": "遍",
     "start": 237.886,
     "end": 238.074
    }
   ],
   "subs": [
    {
     "text": "第六步，检查：先看截图、片段",
     "start": 232.98,
     "end": 236.577
    },
    {
     "text": "再带声音完整看一遍",
     "start": 236.577,
     "end": 238.224
    }
   ]
  },
  {
   "id": "s20_ship.2",
   "scene": "s20_ship",
   "text": "模型看不了视频，就让它先截成图片再看。",
   "start": 238.294,
   "end": 241.384,
   "words": [
    {
     "w": "模型",
     "start": 238.294,
     "end": 238.648
    },
    {
     "w": "看",
     "start": 238.672,
     "end": 238.849
    },
    {
     "w": "不了",
     "start": 238.849,
     "end": 239.002
    },
    {
     "w": "视频",
     "start": 239.014,
     "end": 239.568
    },
    {
     "w": "就",
     "start": 239.898,
     "end": 240.051
    },
    {
     "w": "让",
     "start": 240.051,
     "end": 240.146
    },
    {
     "w": "它",
     "start": 240.146,
     "end": 240.228
    },
    {
     "w": "先",
     "start": 240.24,
     "end": 240.441
    },
    {
     "w": "截成",
     "start": 240.441,
     "end": 240.771
    },
    {
     "w": "图片",
     "start": 240.783,
     "end": 241.066
    },
    {
     "w": "再",
     "start": 241.077,
     "end": 241.172
    },
    {
     "w": "看",
     "start": 241.172,
     "end": 241.384
    }
   ],
   "subs": [
    {
     "text": "模型看不了视频，就让它先截成图片再看",
     "start": 238.294,
     "end": 241.534
    }
   ]
  },
  {
   "id": "s20_ship.3",
   "scene": "s20_ship",
   "text": "你的第一支，先做 15 到 30 秒就够了。",
   "start": 241.604,
   "end": 244.528,
   "words": [
    {
     "w": "你的第一",
     "start": 241.604,
     "end": 242.076
    },
    {
     "w": "支",
     "start": 242.076,
     "end": 242.418
    },
    {
     "w": "先",
     "start": 242.642,
     "end": 242.925
    },
    {
     "w": "做",
     "start": 242.925,
     "end": 243.066
    },
    {
     "w": "15 到 30 秒",
     "start": 243.09,
     "end": 243.998
    },
    {
     "w": "就",
     "start": 244.021,
     "end": 244.139
    },
    {
     "w": "够",
     "start": 244.139,
     "end": 244.34
    },
    {
     "w": "了",
     "start": 244.34,
     "end": 244.528
    }
   ],
   "subs": [
    {
     "text": "你的第一支，先做 15 到 30 秒就够了",
     "start": 241.604,
     "end": 244.678
    }
   ]
  },
  {
   "id": "s21_meta.1",
   "scene": "s21_meta",
   "text": "最后揭个底：这支片子，也是这么做的。",
   "start": 248.48,
   "end": 251.746,
   "words": [
    {
     "w": "最后",
     "start": 248.48,
     "end": 248.787
    },
    {
     "w": "揭",
     "start": 248.81,
     "end": 248.964
    },
    {
     "w": "个",
     "start": 248.964,
     "end": 249.081
    },
    {
     "w": "底",
     "start": 249.081,
     "end": 249.435
    },
    {
     "w": "这",
     "start": 249.824,
     "end": 249.989
    },
    {
     "w": "支",
     "start": 249.989,
     "end": 250.084
    },
    {
     "w": "片子",
     "start": 250.096,
     "end": 250.78
    },
    {
     "w": "也",
     "start": 250.98,
     "end": 251.169
    },
    {
     "w": "是",
     "start": 251.169,
     "end": 251.263
    },
    {
     "w": "这么",
     "start": 251.275,
     "end": 251.416
    },
    {
     "w": "做",
     "start": 251.428,
     "end": 251.605
    },
    {
     "w": "的",
     "start": 251.605,
     "end": 251.746
    }
   ],
   "subs": [
    {
     "text": "最后揭个底：这支片子，也是这么做的",
     "start": 248.48,
     "end": 251.897
    }
   ]
  },
  {
   "id": "s21_meta.2",
   "scene": "s21_meta",
   "text": "Opus 5.5 在 Claude Code 里，写了场景、时间轴和配乐程序。",
   "start": 251.966,
   "end": 256.801,
   "words": [
    {
     "w": "Opus",
     "start": 251.966,
     "end": 252.485
    },
    {
     "w": "5.5",
     "start": 252.497,
     "end": 253.028
    },
    {
     "w": "在",
     "start": 253.122,
     "end": 253.299
    },
    {
     "w": "Claude",
     "start": 253.311,
     "end": 253.653
    },
    {
     "w": "Code",
     "start": 253.665,
     "end": 253.936
    },
    {
     "w": "里",
     "start": 253.936,
     "end": 254.148
    },
    {
     "w": "写",
     "start": 254.36,
     "end": 254.561
    },
    {
     "w": "了",
     "start": 254.561,
     "end": 254.632
    },
    {
     "w": "场景",
     "start": 254.643,
     "end": 255.08
    },
    {
     "w": "时间",
     "start": 255.268,
     "end": 255.669
    },
    {
     "w": "轴",
     "start": 255.669,
     "end": 255.941
    },
    {
     "w": "和",
     "start": 256.035,
     "end": 256.188
    },
    {
     "w": "配乐",
     "start": 256.2,
     "end": 256.412
    },
    {
     "w": "程序",
     "start": 256.424,
     "end": 256.801
    }
   ],
   "subs": [
    {
     "text": "Opus 5.5 在 Claude Code 里",
     "start": 251.966,
     "end": 254.36
    },
    {
     "text": "写了场景、时间轴和配乐程序",
     "start": 254.36,
     "end": 256.951
    }
   ]
  },
  {
   "id": "s21_meta.3",
   "scene": "s21_meta",
   "text": "浏览器逐帧截图，连我的声音，也是合成的。",
   "start": 257.021,
   "end": 260.771,
   "words": [
    {
     "w": "浏览器",
     "start": 257.021,
     "end": 257.552
    },
    {
     "w": "逐帧",
     "start": 257.576,
     "end": 257.882
    },
    {
     "w": "截图",
     "start": 257.894,
     "end": 258.448
    },
    {
     "w": "连",
     "start": 258.743,
     "end": 258.967
    },
    {
     "w": "我",
     "start": 258.967,
     "end": 259.12
    },
    {
     "w": "的",
     "start": 259.12,
     "end": 259.191
    },
    {
     "w": "声音",
     "start": 259.203,
     "end": 259.639
    },
    {
     "w": "也",
     "start": 259.993,
     "end": 260.146
    },
    {
     "w": "是",
     "start": 260.146,
     "end": 260.253
    },
    {
     "w": "合成",
     "start": 260.264,
     "end": 260.595
    },
    {
     "w": "的",
     "start": 260.595,
     "end": 260.771
    }
   ],
   "subs": [
    {
     "text": "浏览器逐帧截图，连我的声音，也是合成的",
     "start": 257.021,
     "end": 260.921
    }
   ]
  },
  {
   "id": "s22_end.1",
   "scene": "s22_end",
   "text": "完整文章和全部 5,181 个案例，都在 WaytoAGI，去做你的第一支吧。",
   "start": 263.06,
   "end": 268.579,
   "words": [
    {
     "w": "完整",
     "start": 263.06,
     "end": 263.402
    },
    {
     "w": "文章",
     "start": 263.414,
     "end": 263.85
    },
    {
     "w": "和",
     "start": 263.944,
     "end": 264.121
    },
    {
     "w": "全部",
     "start": 264.133,
     "end": 264.463
    },
    {
     "w": "5181 个",
     "start": 264.487,
     "end": 265.477
    },
    {
     "w": "案例",
     "start": 265.489,
     "end": 265.843
    },
    {
     "w": "都",
     "start": 266.114,
     "end": 266.268
    },
    {
     "w": "在",
     "start": 266.268,
     "end": 266.385
    },
    {
     "w": "Way",
     "start": 266.409,
     "end": 266.633
    },
    {
     "w": "to",
     "start": 266.645,
     "end": 266.81
    },
    {
     "w": "AGI",
     "start": 266.822,
     "end": 267.329
    },
    {
     "w": "去",
     "start": 267.494,
     "end": 267.683
    },
    {
     "w": "做",
     "start": 267.683,
     "end": 267.777
    },
    {
     "w": "你的第一",
     "start": 267.789,
     "end": 268.237
    },
    {
     "w": "支",
     "start": 268.237,
     "end": 268.367
    },
    {
     "w": "吧",
     "start": 268.367,
     "end": 268.579
    }
   ],
   "subs": [
    {
     "text": "完整文章和全部 5,181 个案例",
     "start": 263.06,
     "end": 265.607
    },
    {
     "text": "都在 WaytoAGI，去做你的第一支吧",
     "start": 265.607,
     "end": 268.729
    }
   ]
  }
 ],
 "chapters": [
  {
   "id": "c0",
   "num": "00",
   "label": "开场",
   "start": 0.0,
   "end": 18.5
  },
  {
   "id": "c1",
   "num": "01",
   "label": "原理",
   "start": 18.5,
   "end": 47.0
  },
  {
   "id": "c2",
   "num": "02",
   "label": "为什么炫",
   "start": 47.0,
   "end": 170.0
  },
  {
   "id": "c3",
   "num": "03",
   "label": "小白上手",
   "start": 170.0,
   "end": 248.0
  },
  {
   "id": "c4",
   "num": "04",
   "label": "幕后",
   "start": 248.0,
   "end": 271.0
  }
 ]
};
